# **Introducción al análisis de datos en Python** 
#### Profesor: Santiago Neira

## Clase 3. Pandas
Una de las habilidades más relevantes para un Data Analyst o un Data Scientist es el manejo de datos estructurados. En este tutorial aprenderá cómo importar archivos a Python para crear `DataFrames` y de esta forma manipularlos para que estos queden en el formato más conveniente para su análisis.

## Introducción a Pandas

###  ¿Qué es Pandas?
Pandas es una librería de código abierto para Python que proporciona herramientas de análisis de datos de alto rendimiento y fáciles de usar. Está construida sobre la biblioteca NumPy y proporciona estructuras de datos de alto nivel para trabajar con datos estructurados y tabulares, como hojas de cálculo y bases de datos relacionales.

Algunas de las características más importantes de Pandas son:

- Ofrece estructuras de datos para trabajar con datos tabulares, como el DataFrame y la Serie.
- Proporciona herramientas para la lectura y escritura de datos desde y hacia una variedad de formatos de archivo, como CSV, Excel, SQL, entre otros.
- Permite realizar operaciones de limpieza y preprocesamiento de datos, como la eliminación de valores perdidos o la normalización de datos.
- Ofrece una amplia variedad de métodos para el análisis de datos, como el agrupamiento, la agregación, la selección y el filtrado de datos.
- Permite la visualización de datos con la integración con otras bibliotecas de Python, como Matplotlib.

Pandas es ampliamente utilizado en ciencia de datos, finanzas, ingeniería y otras disciplinas que requieren la manipulación y el análisis de grandes conjuntos de datos. Es una de las herramientas más populares en Python para el análisis de datos debido a su facilidad de uso y su amplia gama de funciones.

En el siguiente diagrama se puede ver la estructura general de un `dataframe`, es muy similar a un Excel pero solo con una hoja. En este caso las filas representan observaciones y las columnas representan variables.

<center>
<img src="img/dataframe.png" alt="dataframe" width="500" height="300">
</center>

Comenzaremos nuestra introducción a `Pandas` creando nuestro primer `dataframe` con un diccionario.

In [2]:
!pip3 install pandas

Requirement already satisfied: pandas in c:\users\santiago neira\appdata\local\programs\python\python311\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\santiago neira\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\santiago neira\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\santiago neira\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\santiago neira\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\santiago neira\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
#%pip3 install pandas

In [145]:
import pandas as pd

In [146]:
# Cada variable de nuestro dataframe partirá de una lista
nombres = ["Jose", "Esteban", "Elena", "Ana", "Julian", "Juan"]
sexo = ["M", "M", "F", "F", "M", None]
edad = [24, 25, 32, 45, 52, 20]
peso = [75, 80, 60, 86, 72, 70]

In [147]:
# Creamos un diccionario con toda la información
un_diccionario = {
    "nombres": nombres,
    "sexo": sexo,
    "edad": edad,
    "peso": peso
}

In [148]:
un_diccionario

{'nombres': ['Jose', 'Esteban', 'Elena', 'Ana', 'Julian', 'Juan'],
 'sexo': ['M', 'M', 'F', 'F', 'M', None],
 'edad': [24, 25, 32, 45, 52, 20],
 'peso': [75, 80, 60, 86, 72, 70]}

In [149]:
# Construimos nuestro primer dataframe
data = pd.DataFrame(un_diccionario)

In [150]:
# Visualizamos nuestro dataframe
data

   nombres  sexo  edad  peso
0     Jose     M    24    75
1  Esteban     M    25    80
2    Elena     F    32    60
3      Ana     F    45    86
4   Julian     M    52    72
5     Juan  None    20    70

El `dataframe` es un objeto en Python que tiene unos atributos especiales. Estos atributos nos sirven para estudiar las características de nuestro objeto. Los principales se listan a continuación: 

- `.index`: es una propiedad que devuelve una lista con los nombres de fila del dataframe.

- `.columns`: es una propiedad que devuelve una lista con los nombres de las columnas del dataframe.

- `.shape`: es una propiedad que devuelve una tupla que indica el número de filas y columnas en el dataframe. Por ejemplo, un dataframe con 100 filas y 5 columnas tendría una forma de (100, 5).

- `.size`: es una propiedad que devuelve la cantidad de datos o celdas del dataframe. Por ejemplo, un dataframe con 100 filas y 5 columnas tendría un `size` de $100\times5=500$.

- `.count()`: este método cuenta la cantidad de valores no nulos por columna o fila.

- `.values`: es una propiedad que devuelve un array NumPy que contiene los valores del dataframe.

- `.T`: es un atributo que devuelve la base traspuesta.

- `.dtypes`: es una propiedad que devuelve un objeto que describe los tipos de datos de cada columna.

- `.head(n)`: es un método que devuelve las primeras n filas del dataframe.

- `.tail(n)`: es un método que devuelve las últimas n filas del dataframe.

- `.info()`: es un método que muestra información sobre el dataframe, incluyendo su forma, los tipos de datos de cada columna y la cantidad de valores no nulos.

- `.describe()`: es un método que muestra estadísticas descriptivas sobre el dataframe, incluyendo la media, la mediana, la desviación estándar, etc.

A continuación estudiaremos a detalle cada uno de estos métodos y atributos.

In [151]:
data

   nombres  sexo  edad  peso
0     Jose     M    24    75
1  Esteban     M    25    80
2    Elena     F    32    60
3      Ana     F    45    86
4   Julian     M    52    72
5     Juan  None    20    70

In [152]:
# .index Estudiamos los nombres del índice
data.index

RangeIndex(start=0, stop=6, step=1)

In [153]:
# .columns ¿Cuáles son los nombres de las columnas?
data.columns

Index(['nombres', 'sexo', 'edad', 'peso'], dtype='object')

In [154]:
# .shape ¿Cuáles son las dimensiones del dataframe?
data.shape

(6, 4)

In [155]:
# .size ¿Cuántos datos tengo?
data.size

24

In [156]:
# .count() ¿Cuántos datos no nulos tengo por columna?
data.count()

nombres    6
sexo       5
edad       6
peso       6
dtype: int64

In [157]:
data

   nombres  sexo  edad  peso
0     Jose     M    24    75
1  Esteban     M    25    80
2    Elena     F    32    60
3      Ana     F    45    86
4   Julian     M    52    72
5     Juan  None    20    70

In [158]:
# .count() ¿Cuántos datos no nulos tengo por fila/observación/individuo?
data.count(axis = 1)

0    4
1    4
2    4
3    4
4    4
5    3
dtype: int64

In [159]:
# axis = 0 calcula las funciones por columna. Esta es la opción por default
# axis = 1 calcula las funciones por fila
data.count(axis = 0)

nombres    6
sexo       5
edad       6
peso       6
dtype: int64

In [160]:
# .values Convierte el dataframe en un np.array de dos dimensiones
data.values

array([['Jose', 'M', 24, 75],
       ['Esteban', 'M', 25, 80],
       ['Elena', 'F', 32, 60],
       ['Ana', 'F', 45, 86],
       ['Julian', 'M', 52, 72],
       ['Juan', None, 20, 70]], dtype=object)

In [161]:
data

   nombres  sexo  edad  peso
0     Jose     M    24    75
1  Esteban     M    25    80
2    Elena     F    32    60
3      Ana     F    45    86
4   Julian     M    52    72
5     Juan  None    20    70

In [162]:
# .T Trasponer
data.T

            0        1      2    3       4     5
nombres  Jose  Esteban  Elena  Ana  Julian  Juan
sexo        M        M      F    F       M  None
edad       24       25     32   45      52    20
peso       75       80     60   86      72    70

In [163]:
data

   nombres  sexo  edad  peso
0     Jose     M    24    75
1  Esteban     M    25    80
2    Elena     F    32    60
3      Ana     F    45    86
4   Julian     M    52    72
5     Juan  None    20    70

In [164]:
data_transpuesta = data.T

In [165]:
data_transpuesta

            0        1      2    3       4     5
nombres  Jose  Esteban  Elena  Ana  Julian  Juan
sexo        M        M      F    F       M  None
edad       24       25     32   45      52    20
peso       75       80     60   86      72    70

In [166]:
data.T.index

Index(['nombres', 'sexo', 'edad', 'peso'], dtype='object')

In [167]:
data.T.columns

RangeIndex(start=0, stop=6, step=1)

In [168]:
data

   nombres  sexo  edad  peso
0     Jose     M    24    75
1  Esteban     M    25    80
2    Elena     F    32    60
3      Ana     F    45    86
4   Julian     M    52    72
5     Juan  None    20    70

In [169]:
# .dtypes ¿Cuál es el tipo de cada variable?
data.dtypes

nombres    object
sexo       object
edad        int64
peso        int64
dtype: object

In [170]:
# .head() por defecto entrega las primeras 5 filas
data.head()

   nombres sexo  edad  peso
0     Jose    M    24    75
1  Esteban    M    25    80
2    Elena    F    32    60
3      Ana    F    45    86
4   Julian    M    52    72

In [171]:
# Primera fila
data.head(1)

  nombres sexo  edad  peso
0    Jose    M    24    75

In [172]:
# Primeras dos filas
data.head(2)

   nombres sexo  edad  peso
0     Jose    M    24    75
1  Esteban    M    25    80

In [173]:
# .tail() Por defecto devuelve las últimas 5 filas
data.tail()

   nombres  sexo  edad  peso
1  Esteban     M    25    80
2    Elena     F    32    60
3      Ana     F    45    86
4   Julian     M    52    72
5     Juan  None    20    70

In [174]:
# Última fila
data.tail(1)

  nombres  sexo  edad  peso
5    Juan  None    20    70

In [175]:
# Últimas dos filas
data.tail(2)

  nombres  sexo  edad  peso
4  Julian     M    52    72
5    Juan  None    20    70

In [176]:
# .info() descripción general de la estructura de la base
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nombres  6 non-null      object
 1   sexo     5 non-null      object
 2   edad     6 non-null      int64
 3   peso     6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [177]:
# .describe() Estadísticas descriptivas de la data
data.describe()

            edad       peso
count   6.000000   6.000000
mean   33.000000  73.833333
std    12.806248   8.908797
min    20.000000  60.000000
25%    24.250000  70.500000
50%    28.500000  73.500000
75%    41.750000  78.750000
max    52.000000  86.000000

In [178]:
data

   nombres  sexo  edad  peso
0     Jose     M    24    75
1  Esteban     M    25    80
2    Elena     F    32    60
3      Ana     F    45    86
4   Julian     M    52    72
5     Juan  None    20    70

In [179]:
data.describe(include = "object")

       nombres sexo
count        6    5
unique       6    2
top       Jose    M
freq         1    3

In [180]:
data.describe(include = "all")

       nombres sexo       edad       peso
count        6    5   6.000000   6.000000
unique       6    2        NaN        NaN
top       Jose    M        NaN        NaN
freq         1    3        NaN        NaN
mean       NaN  NaN  33.000000  73.833333
std        NaN  NaN  12.806248   8.908797
min        NaN  NaN  20.000000  60.000000
25%        NaN  NaN  24.250000  70.500000
50%        NaN  NaN  28.500000  73.500000
75%        NaN  NaN  41.750000  78.750000
max        NaN  NaN  52.000000  86.000000

### Indexación y ejes
Adicionalmente, para manipular los dataframes es importante aprender como extraer fracciones de nuestra información. A esto se le conoce generalmente como *slicing*. En esta sección aprenderemos a filtrar la data por columnas y por filas. Los métodos que veremos serán.

- `[{nombre de la columna}]` y `.{nombre de la columna}`: Extracción de columnas.

- `set_index()`: Convertir una columna como índice.

- `.loc[]`: es un método para acceder a filas y columnas del dataframe por etiquetas de fila y columna.

- `.iloc[]`: es un método para acceder a filas y columnas del dataframe por índice entero.

- `.groupby()`: es un método para agrupar los datos por una o más columnas y realizar cálculos sobre los grupos resultantes.

- `.reset_index()`: Reiniciar el índice para que sea una enumeración de las filas.

- `.sort_values()`: Re-ordenar las filas.

- `.rename()`: Cambiarle el nombre a una fila o una columna.

- `.unique()`: Devuelve los valores únicos de la columna.

- `.value_counts()`: Cuenta la cantidad de valores únicos por columna.

**Extraer columnas**

Para extraer columnas tenemos dos métodos.
1. El primero consiste escribir entre corchetes cuadrados (`[]`) el nombre de la columna que se desea extraer entre comillas. Este método también permite extraer más de una columnas. Si ese es el caso, se pondría entre los corchetes cuadrados una lista con los nombres de las columnas deseadas entre comillas y separadas por comas.
2. El segundo método consiste en poner el nombre de la columna que se quiere extraer después de un punto `.`. Este método solo sirve si el nombre no está separado por espacios o caracteres especiales.

In [181]:
data

   nombres  sexo  edad  peso
0     Jose     M    24    75
1  Esteban     M    25    80
2    Elena     F    32    60
3      Ana     F    45    86
4   Julian     M    52    72
5     Juan  None    20    70

In [182]:
# Método 1
data["nombres"]

0       Jose
1    Esteban
2      Elena
3        Ana
4     Julian
5       Juan
Name: nombres, dtype: object

In [183]:
# Método 1
data[["nombres", "peso"]]

   nombres  peso
0     Jose    75
1  Esteban    80
2    Elena    60
3      Ana    86
4   Julian    72
5     Juan    70

In [184]:
columnas_deseadas = ['nombres', "peso"]
data[columnas_deseadas]

   nombres  peso
0     Jose    75
1  Esteban    80
2    Elena    60
3      Ana    86
4   Julian    72
5     Juan    70

In [185]:
# Método 2
data.nombres

0       Jose
1    Esteban
2      Elena
3        Ana
4     Julian
5       Juan
Name: nombres, dtype: object

In [186]:
data.columns

Index(['nombres', 'sexo', 'edad', 'peso'], dtype='object')

In [187]:
data.sexo

0       M
1       M
2       F
3       F
4       M
5    None
Name: sexo, dtype: object

In [188]:
data

   nombres  sexo  edad  peso
0     Jose     M    24    75
1  Esteban     M    25    80
2    Elena     F    32    60
3      Ana     F    45    86
4   Julian     M    52    72
5     Juan  None    20    70

In [189]:
# Convertir una columna como un índice
data_con_indice_nombre = data.set_index('nombres')

In [190]:
data_con_indice_nombre

         sexo  edad  peso
nombres
Jose        M    24    75
Esteban     M    25    80
Elena       F    32    60
Ana         F    45    86
Julian      M    52    72
Juan     None    20    70

In [191]:
data_con_indice_nombre.index

Index(['Jose', 'Esteban', 'Elena', 'Ana', 'Julian', 'Juan'], dtype='object', name='nombres')

In [192]:
data.set_index('nombres')

         sexo  edad  peso
nombres
Jose        M    24    75
Esteban     M    25    80
Elena       F    32    60
Ana         F    45    86
Julian      M    52    72
Juan     None    20    70

In [193]:
data['peso']

0    75
1    80
2    60
3    86
4    72
5    70
Name: peso, dtype: int64

In [194]:
# Si no sobreescribimos el objeto, no se guardan los cambios
data = data.set_index('nombres')
data

         sexo  edad  peso
nombres
Jose        M    24    75
Esteban     M    25    80
Elena       F    32    60
Ana         F    45    86
Julian      M    52    72
Juan     None    20    70

In [195]:
# Otra forma de sobreescribir el objeto sin necesidad de asignarlo es usando el argumento inplace = True, dentro
# de las funciones de Pandas
data.set_index("sexo", append = True, inplace = True)
data

              edad  peso
nombres sexo
Jose    M       24    75
Esteban M       25    80
Elena   F       32    60
Ana     F       45    86
Julian  M       52    72
Juan    NaN     20    70

In [196]:
# Para resetar el índice usamos .reset_index()
data.reset_index(inplace = True)
data

   nombres sexo  edad  peso
0     Jose    M    24    75
1  Esteban    M    25    80
2    Elena    F    32    60
3      Ana    F    45    86
4   Julian    M    52    72
5     Juan  NaN    20    70

In [197]:
data

   nombres sexo  edad  peso
0     Jose    M    24    75
1  Esteban    M    25    80
2    Elena    F    32    60
3      Ana    F    45    86
4   Julian    M    52    72
5     Juan  NaN    20    70

In [198]:
# Vuelva nombres el índice
data.set_index("nombres", inplace = True)

In [199]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70

In [200]:
# Ordene por edad de menor a mayor. No guarde el valor
data.sort_values(['peso','edad'])

        sexo  edad  peso
nombres
Elena      F    32    60
Juan     NaN    20    70
Julian     M    52    72
Jose       M    24    75
Esteban    M    25    80
Ana        F    45    86

In [201]:
# Ordene por edad de mayor a menor. No guarde el valor
data.sort_values('edad', ascending = False)

# Note que los índices se movieron!

        sexo  edad  peso
nombres
Julian     M    52    72
Ana        F    45    86
Elena      F    32    60
Esteban    M    25    80
Jose       M    24    75
Juan     NaN    20    70

In [202]:
# Cambie el nombre de la columna sexo a género
data.rename(columns = {"sexo": "género"})

        género  edad  peso
nombres
Jose         M    24    75
Esteban      M    25    80
Elena        F    32    60
Ana          F    45    86
Julian       M    52    72
Juan       NaN    20    70

In [203]:
data_renombrada= data.rename(columns = {"sexo": "género", "peso":"peso (Kg)"
                                        })

In [204]:
data_renombrada

        género  edad  peso (Kg)
nombres
Jose         M    24         75
Esteban      M    25         80
Elena        F    32         60
Ana          F    45         86
Julian       M    52         72
Juan       NaN    20         70

In [205]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70

In [206]:
data["sexo"].unique() ### MUY útil para conocer las categorías de una variable

array(['M', 'F', nan], dtype=object)

In [207]:
# Valores únicos de la columna sexo
data.sexo.unique()

array(['M', 'F', nan], dtype=object)

In [208]:
len(data.edad.unique())

6

In [209]:
data.edad.nunique()

6

In [210]:
# ¿Cuántos hombres y mujeres tenemos?
data["sexo"].value_counts(dropna=False)

sexo
M      3
F      2
NaN    1
Name: count, dtype: int64

In [211]:
data['edad'].value_counts()

edad
24    1
25    1
32    1
45    1
52    1
20    1
Name: count, dtype: int64

In [212]:
# Incluya los valores faltantes en el conteo
#dropna: drop nan - eliminar los valores nulos
data["sexo"].value_counts(dropna = False)

sexo
M      3
F      2
NaN    1
Name: count, dtype: int64

In [213]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70

In [214]:
data["sexo"].value_counts(normalize = True)

sexo
M    0.6
F    0.4
Name: proportion, dtype: float64

In [215]:
# ¿Cuál es la proporción de hombres y mujeres tenemos?
data["sexo"].value_counts(normalize = True,dropna = False)

sexo
M      0.500000
F      0.333333
NaN    0.166667
Name: proportion, dtype: float64

Los métodos `.iloc` y ``.loc`` son utilizados en Pandas para acceder a los datos de un dataframe de diferentes maneras.

`.iloc` se utiliza para acceder a los datos del dataframe mediante índices enteros. Permite seleccionar filas y columnas utilizando números enteros en lugar de etiquetas de fila y columna. La sintaxis general para utilizar `.iloc` es la siguiente:

```python
dataframe.iloc[filas, columnas]
```

Donde `filas` y `columnas` son listas o arrays de números enteros que indican las filas y columnas que se desean seleccionar, respectivamente.

<center>
<div>
<img src="img/iloc2.png" width="500"/>
</div>
</center>

Por ejemplo, para seleccionar las primeras 3 filas y las primeras 2 columnas de un dataframe, se puede utilizar el siguiente código:

```python 
dataframe.iloc[:3, :2]
```

Recuerde que la indexación en python empieza en 0. A continuación puede encontrar una referencia gráfica:
<center>
<img src="img/iloc1.png" alt="indexación" width="450" height="200">
</center>

Por otro lado, `.loc` se utiliza para acceder a los datos del dataframe mediante etiquetas de fila y columna. Permite seleccionar filas y columnas utilizando las etiquetas de fila y columna en lugar de índices enteros. La sintaxis general para utilizar `.loc` es la siguiente:

```python
dataframe.loc[filas, columnas]
```

Donde `filas` y `columnas` son listas o arrays de etiquetas de fila y columna que indican las filas y columnas que se desean seleccionar, respectivamente.

<center>
<div>
<img src="img/iloc3.png" width="500"/>
</div>
</center>

Por ejemplo, para seleccionar todas las filas donde la columna "edad" es mayor o igual a 30, se puede utilizar el siguiente código:

```python
dataframe.loc[dataframe['edad'] >= 30, :]
```

En resumen, `.iloc` se utiliza para acceder a los datos mediante índices enteros, mientras que `.loc` se utiliza para acceder a los datos mediante etiquetas de fila y columna. Ambos métodos son muy útiles para la selección y manipulación de datos en Pandas.

In [216]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70

In [217]:
data.columns

Index(['sexo', 'edad', 'peso'], dtype='object')

In [218]:
data.iloc[1,1]

np.int64(25)

In [219]:
data.iloc[:4,1:]

         edad  peso
nombres
Jose       24    75
Esteban    25    80
Elena      32    60
Ana        45    86

In [220]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70

In [221]:
# Extraiga la fila de Ana usando .loc
data.loc['Ana',['edad','sexo']]

edad    45
sexo     F
Name: Ana, dtype: object

In [222]:
## Qué persona tiene 45 años?
data.loc[data.edad == 45]

        sexo  edad  peso
nombres
Ana        F    45    86

In [225]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70

In [226]:
data.loc[data.sexo=='F']

        sexo  edad  peso
nombres
Elena      F    32    60
Ana        F    45    86

In [223]:
data_filtrada=data.loc[data.edad>30]
data_filtrada[['sexo','peso']]

        sexo  peso
nombres
Elena      F    60
Ana        F    86
Julian     M    72

In [227]:
data.loc[(data.edad>25)&(data.sexo=='F')]

        sexo  edad  peso
nombres
Elena      F    32    60
Ana        F    45    86

In [228]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70

In [229]:
data.loc[data.sexo == "F"]

        sexo  edad  peso
nombres
Elena      F    32    60
Ana        F    45    86

In [230]:
data.loc[data.peso > 50]

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70

In [231]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70

In [232]:
data.loc[data.sexo=='M',:]

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Julian     M    52    72

In [233]:
data.loc[data.sexo=='M',:].describe()

            edad       peso
count   3.000000   3.000000
mean   33.666667  75.666667
std    15.885003   4.041452
min    24.000000  72.000000
25%    24.500000  73.500000
50%    25.000000  75.000000
75%    38.500000  77.500000
max    52.000000  80.000000

In [234]:
data.loc[data.sexo=='M'].sort_values('peso')

        sexo  edad  peso
nombres
Julian     M    52    72
Jose       M    24    75
Esteban    M    25    80

In [235]:
data_filtrada = data.loc[data.sexo=='M']
data_filtrada.sort_values('peso')

        sexo  edad  peso
nombres
Julian     M    52    72
Jose       M    24    75
Esteban    M    25    80

In [236]:
datos_transpuesto = data.T

In [237]:
datos_transpuesto

nombres Jose Esteban Elena Ana Julian Juan
sexo       M       M     F   F      M  NaN
edad      24      25    32  45     52   20
peso      75      80    60  86     72   70

In [238]:
datos_transpuesto['Gelver'] = ['M',32,78]

In [239]:
datos_transpuesto

nombres Jose Esteban Elena Ana Julian Juan Gelver
sexo       M       M     F   F      M  NaN      M
edad      24      25    32  45     52   20     32
peso      75      80    60  86     72   70     78

In [240]:
datos_transpuesto.loc[:, 'Gelver']

sexo     M
edad    32
peso    78
Name: Gelver, dtype: object

In [241]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70

In [242]:
# Extraiga la columna de edad usando .loc
data.loc[:,'edad']

nombres
Jose       24
Esteban    25
Elena      32
Ana        45
Julian     52
Juan       20
Name: edad, dtype: int64

In [243]:
# Extraiga los pesos de Juan y Esteban usando .loc
data.loc[['Juan', 'Esteban'], ['peso','edad']]

         peso  edad
nombres
Juan       70    20
Esteban    80    25

In [244]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70

In [245]:
data['edad']>30

nombres
Jose       False
Esteban    False
Elena       True
Ana         True
Julian      True
Juan       False
Name: edad, dtype: bool

In [246]:
data.loc[data['edad']>30,:]

        sexo  edad  peso
nombres
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72

In [247]:
data.loc[data['peso']>70]

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Ana        F    45    86
Julian     M    52    72

In [248]:
data.loc[(data['edad'] > 30) & (data['sexo'] == 'M')]

        sexo  edad  peso
nombres
Julian     M    52    72

In [249]:
# Extraiga a todas las personas de sexo masculino mayores a 30 años
data.loc[(data['edad'] > 30) | (data['sexo'] == 'M'),:]

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72

In [250]:
data.loc[(data['edad'] > 30) & (data['sexo'] == 'M')]

        sexo  edad  peso
nombres
Julian     M    52    72

In [251]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70

In [252]:
# Extraiga la segunda fila usando .iloc
data.iloc[1]

sexo     M
edad    25
peso    80
Name: Esteban, dtype: object

In [253]:
data.iloc[1,]

sexo     M
edad    25
peso    80
Name: Esteban, dtype: object

In [254]:
# Extraiga la segunda y tercera columna usando .iloc
data.iloc[:,[1,2]]

         edad  peso
nombres
Jose       24    75
Esteban    25    80
Elena      32    60
Ana        45    86
Julian     52    72
Juan       20    70

In [255]:
# Extraiga la primera y última fila y segunda columna usando .iloc
data.iloc[[0,-1],[1]]

         edad
nombres
Jose       24
Juan       20

In [256]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70

In [257]:
data.iloc[-1,-1]

np.int64(70)

In [258]:
# Reinicie el índice
data.reset_index(inplace = True, drop = False) 
data

   nombres sexo  edad  peso
0     Jose    M    24    75
1  Esteban    M    25    80
2    Elena    F    32    60
3      Ana    F    45    86
4   Julian    M    52    72
5     Juan  NaN    20    70

In [259]:
data_ana=data.loc[data['nombres']=='Ana']
data_ana[['sexo', 'peso']]

  sexo  peso
3    F    86

In [260]:
data.loc[data.nombres=='Ana', ['sexo', 'peso']]

  sexo  peso
3    F    86

## Pandas intermedio

### Modificación de valores
Las columnas dentro de un dataframe a su vez son un objeto. Estos se conocen como `Series` y son una estructura de datos unidimensional que contiene una secuencia de valores y una etiqueta de índice para cada uno de ellos. Se puede pensar en una serie como una columna en una hoja de cálculo o como un array unidimensional con etiquetas de índice.

Una serie de Pandas se puede crear a partir de una lista, un array NumPy, un diccionario o incluso otro objeto de serie. La etiqueta de índice por defecto para cada elemento de la serie es simplemente un rango de números enteros de 0 a n-1, donde n es el número de elementos en la serie. Sin embargo, se puede especificar etiquetas de índice personalizadas para cada elemento de la serie.

In [261]:
type(data["nombres"])

pandas.core.series.Series

In [262]:
data

   nombres sexo  edad  peso
0     Jose    M    24    75
1  Esteban    M    25    80
2    Elena    F    32    60
3      Ana    F    45    86
4   Julian    M    52    72
5     Juan  NaN    20    70

Podemos comenzar editando valores o celdas particulares. Por ejemplo, el sexooo de Juan está como nulo. Vamos a definirlo como masculino

In [264]:
data.loc[data.nombres == "Juan", "sexo"]

5    NaN
Name: sexo, dtype: object

In [265]:
data.loc[data.nombres == "Juan", "sexo"] = "M"

In [266]:
data

   nombres sexo  edad  peso
0     Jose    M    24    75
1  Esteban    M    25    80
2    Elena    F    32    60
3      Ana    F    45    86
4   Julian    M    52    72
5     Juan    M    20    70

Del mismo modo, también podemos editar columnas. Actualmente tenemos la edad en años, pasemosla a días.

In [267]:
data["edad"]*365

0     8760
1     9125
2    11680
3    16425
4    18980
5     7300
Name: edad, dtype: int64

In [268]:
data

   nombres sexo  edad  peso
0     Jose    M    24    75
1  Esteban    M    25    80
2    Elena    F    32    60
3      Ana    F    45    86
4   Julian    M    52    72
5     Juan    M    20    70

In [269]:
data["edad"] = data["edad"]*365

In [270]:
data

   nombres sexo   edad  peso
0     Jose    M   8760    75
1  Esteban    M   9125    80
2    Elena    F  11680    60
3      Ana    F  16425    86
4   Julian    M  18980    72
5     Juan    M   7300    70

También podemos crear una nueva variable

In [271]:
import numpy as np

In [272]:
data["nueva_variable"] = [1,2,3,np.nan,np.nan,np.nan]

In [273]:
data

   nombres sexo   edad  peso  nueva_variable
0     Jose    M   8760    75             1.0
1  Esteban    M   9125    80             2.0
2    Elena    F  11680    60             3.0
3      Ana    F  16425    86             NaN
4   Julian    M  18980    72             NaN
5     Juan    M   7300    70             NaN

In [274]:
data_renombrada = data.rename(columns={'edad':'edad(dias)'})
data_renombrada

   nombres sexo  edad(dias)  peso  nueva_variable
0     Jose    M        8760    75             1.0
1  Esteban    M        9125    80             2.0
2    Elena    F       11680    60             3.0
3      Ana    F       16425    86             NaN
4   Julian    M       18980    72             NaN
5     Juan    M        7300    70             NaN

Otro método para crear una nueva variable es usando el método `.assign()`

In [275]:
data = data.assign(nueva_variable2 = np.nan)
data

   nombres sexo   edad  peso  nueva_variable  nueva_variable2
0     Jose    M   8760    75             1.0              NaN
1  Esteban    M   9125    80             2.0              NaN
2    Elena    F  11680    60             3.0              NaN
3      Ana    F  16425    86             NaN              NaN
4   Julian    M  18980    72             NaN              NaN
5     Juan    M   7300    70             NaN              NaN

In [276]:

data['edad'] = data['edad']/365

data['edad_dias'] = data['edad']*365

In [132]:
data

   nombres sexo  edad  peso  nueva_variable  nueva_variable2  edad_dias
0     Jose    M  24.0    75             1.0              NaN     8760.0
1  Esteban    M  25.0    80             2.0              NaN     9125.0
2    Elena    F  32.0    60             3.0              NaN    11680.0
3      Ana    F  45.0    86             NaN              NaN    16425.0
4   Julian    M  52.0    72             NaN              NaN    18980.0
5     Juan    M  20.0    70             NaN              NaN     7300.0

In [277]:
data.loc[data.edad<=24,'nueva_variable'] = 'Rango 1: 18-24'

C:\Users\Santiago Neira\AppData\Local\Temp\ipykernel_33372\4244016696.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Rango 1: 18-24' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data.loc[data.edad<=24,'nueva_variable'] = 'Rango 1: 18-24'

In [278]:
data

   nombres sexo  edad  peso  nueva_variable  nueva_variable2  edad_dias
0     Jose    M  24.0    75  Rango 1: 18-24              NaN     8760.0
1  Esteban    M  25.0    80             2.0              NaN     9125.0
2    Elena    F  32.0    60             3.0              NaN    11680.0
3      Ana    F  45.0    86             NaN              NaN    16425.0
4   Julian    M  52.0    72             NaN              NaN    18980.0
5     Juan    M  20.0    70  Rango 1: 18-24              NaN     7300.0

In [279]:
data.loc[data.edad<=24,'nueva_variable'] = 'Rango 1: 18-24'
data.loc[(data.edad>=25) & (data.edad<=32),'nueva_variable'] = 'Rango 2: 25-32'
data.loc[(data.edad>=33) & (data.edad<=54),'nueva_variable'] = 'Rango 3: 33-54'
data.loc[(data.edad>=55),'nueva_variable'] = 'Rango 4: 55+'
data

   nombres sexo  edad  peso  nueva_variable  nueva_variable2  edad_dias
0     Jose    M  24.0    75  Rango 1: 18-24              NaN     8760.0
1  Esteban    M  25.0    80  Rango 2: 25-32              NaN     9125.0
2    Elena    F  32.0    60  Rango 2: 25-32              NaN    11680.0
3      Ana    F  45.0    86  Rango 3: 33-54              NaN    16425.0
4   Julian    M  52.0    72  Rango 3: 33-54              NaN    18980.0
5     Juan    M  20.0    70  Rango 1: 18-24              NaN     7300.0

El valor con el que se modifica cada variable no tiene que ser el mismo para todas.

In [280]:
apellido = ["Urrutia", "Carvajal", "Gómez", "Tobón", "Pardo", "Lopez"]

In [281]:
data["nombres"] = data["nombres"] + " " + apellido

In [282]:
data

,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,Jose Urrutia,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,Esteban Carvajal,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,Elena Gómez,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,Ana Tobón,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,Julian Pardo,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,Juan Lopez,M,20.0,70,Rango 1: 18-24,NaN,7300.0

### Estadísticas descriptivas
Anteriormente pudimos ver como el método `.describe()` me daba un resumen de toda la base. Sin embargo, en esta sección veremos cada una de las principales funciones para sacar las estadísticas

In [283]:
data.describe()

            edad       peso  nueva_variable2     edad_dias
count   6.000000   6.000000              0.0      6.000000
mean   33.000000  73.833333              NaN  12045.000000
std    12.806248   8.908797              NaN   4674.280693
min    20.000000  60.000000              NaN   7300.000000
25%    24.250000  70.500000              NaN   8851.250000
50%    28.500000  73.500000              NaN  10402.500000
75%    41.750000  78.750000              NaN  15238.750000
max    52.000000  86.000000              NaN  18980.000000

In [284]:
data.sum()

nombres            Jose UrrutiaEsteban CarvajalElena GómezAna Tob...
sexo                                                          MMFFMM
edad                                                           198.0
peso                                                             443
nueva_variable     Rango 1: 18-24Rango 2: 25-32Rango 2: 25-32Rang...
nueva_variable2                                                  0.0
edad_dias                                                    72270.0
dtype: object

In [285]:
# Suma de todas las columnas
data.sum(axis=0)

nombres            Jose UrrutiaEsteban CarvajalElena GómezAna Tob...
sexo                                                          MMFFMM
edad                                                           198.0
peso                                                             443
nueva_variable     Rango 1: 18-24Rango 2: 25-32Rango 2: 25-32Rang...
nueva_variable2                                                  0.0
edad_dias                                                    72270.0
dtype: object

In [286]:
data

,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,Jose Urrutia,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,Esteban Carvajal,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,Elena Gómez,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,Ana Tobón,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,Julian Pardo,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,Juan Lopez,M,20.0,70,Rango 1: 18-24,NaN,7300.0

In [143]:
data.sum(axis=1)

TypeError: can only concatenate str (not "float") to str

In [287]:
data

,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,Jose Urrutia,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,Esteban Carvajal,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,Elena Gómez,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,Ana Tobón,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,Julian Pardo,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,Juan Lopez,M,20.0,70,Rango 1: 18-24,NaN,7300.0

In [288]:
# Suma por fila
data.sum(axis = 1, numeric_only = True)

0     8859.0
1     9230.0
2    11772.0
3    16556.0
4    19104.0
5     7390.0
dtype: float64

In [289]:
# Suma de toda la columna peso
data["peso"].sum()

np.int64(443)

In [290]:
# Dato mínimo por columna
data.min()

nombres                 Ana Tobón
sexo                            F
edad                         20.0
peso                           60
nueva_variable     Rango 1: 18-24
nueva_variable2               NaN
edad_dias                  7300.0
dtype: object

In [291]:
# Dato máximo por columna
data.edad_dias.max()

np.float64(18980.0)

In [292]:
data

,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,Jose Urrutia,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,Esteban Carvajal,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,Elena Gómez,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,Ana Tobón,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,Julian Pardo,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,Juan Lopez,M,20.0,70,Rango 1: 18-24,NaN,7300.0

In [293]:
# ¿Cuál es el id de la persona que tiene la edad mínima?
data.edad.idxmin()

5

In [295]:
# Juan López tiene la edad mínima
data.iloc[data.edad.idxmin(),]

nombres                Juan Lopez
sexo                            M
edad                         20.0
peso                           70
nueva_variable     Rango 1: 18-24
nueva_variable2               NaN
edad_dias                  7300.0
Name: 5, dtype: object

In [296]:
# ¿Cuál es el índice de la persona con mayor peso?
data.peso.idxmax()

3

In [297]:
data.loc[data.peso.idxmax(),]

nombres                 Ana Tobón
sexo                            F
edad                         45.0
peso                           86
nueva_variable     Rango 3: 33-54
nueva_variable2               NaN
edad_dias                 16425.0
Name: 3, dtype: object

In [298]:
data

,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,Jose Urrutia,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,Esteban Carvajal,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,Elena Gómez,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,Ana Tobón,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,Julian Pardo,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,Juan Lopez,M,20.0,70,Rango 1: 18-24,NaN,7300.0

In [299]:
# Media de las variables
data.mean(numeric_only = True)

edad                  33.000000
peso                  73.833333
nueva_variable2             NaN
edad_dias          12045.000000
dtype: float64

In [300]:
data

,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,Jose Urrutia,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,Esteban Carvajal,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,Elena Gómez,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,Ana Tobón,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,Julian Pardo,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,Juan Lopez,M,20.0,70,Rango 1: 18-24,NaN,7300.0

In [301]:
# Datos medianos
data.median(numeric_only = True)

edad                  28.5
peso                  73.5
nueva_variable2        NaN
edad_dias          10402.5
dtype: float64

In [302]:
data.reset_index(inplace=True)

In [303]:
data

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,1,Esteban Carvajal,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,2,Elena Gómez,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,3,Ana Tobón,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,4,Julian Pardo,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,5,Juan Lopez,M,20.0,70,Rango 1: 18-24,NaN,7300.0

In [304]:
data['nombres'] = data['nombres'] + ' López'

In [305]:
data

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia López,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,1,Esteban Carvajal López,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,2,Elena Gómez López,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,3,Ana Tobón López,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,4,Julian Pardo López,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,5,Juan Lopez López,M,20.0,70,Rango 1: 18-24,NaN,7300.0

In [306]:
data.set_index('nombres')

,index,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
nombres,,,,,,,
Jose Urrutia López,0,M,24.0,75,Rango 1: 18-24,NaN,8760.0
Esteban Carvajal López,1,M,25.0,80,Rango 2: 25-32,NaN,9125.0
Elena Gómez López,2,F,32.0,60,Rango 2: 25-32,NaN,11680.0
Ana Tobón López,3,F,45.0,86,Rango 3: 33-54,NaN,16425.0
Julian Pardo López,4,M,52.0,72,Rango 3: 33-54,NaN,18980.0
Juan Lopez López,5,M,20.0,70,Rango 1: 18-24,NaN,7300.0

### Aplicar funciones a las columnas
En Pandas, el método `apply` se utiliza para aplicar una función a una serie o a un dataframe. El método `apply` toma como argumento una función y la aplica a cada elemento de la serie o del dataframe, devolviendo una nueva serie o dataframe con los resultados de la función aplicada a cada elemento.

La función que se aplica en el método `apply` puede ser una función lambda o una función definida por el usuario. Esta función debe tomar como argumento un elemento de la serie o dataframe y devolver el resultado de aplicar la función al elemento.

El método `apply` se puede aplicar de varias formas en un dataframe:

- Aplicar una función a una columna específica: Se puede utilizar el método `apply` en una columna específica de un dataframe utilizando la siguiente sintaxis:

```python
dataframe["nombre_columna"].apply(funcion)
```

Donde "nombre_columna" es el nombre de la columna en la que se desea aplicar la función y "funcion" es la función que se desea aplicar a cada elemento de la columna.

- Aplicar una función a un dataframe completo: Se puede utilizar el método `apply` en un dataframe completo utilizando la siguiente sintaxis:

```python
dataframe.apply(funcion)
```

Donde "funcion" es la función que se desea aplicar a cada elemento del dataframe.

- Aplicar una función a una fila específica: Se puede utilizar el método `apply` en una fila específica de un dataframe utilizando la siguiente sintaxis:

```python
dataframe.loc[etiqueta_fila].apply(funcion)
```

Donde "etiqueta_fila" es la etiqueta de la fila en la que se desea aplicar la función y "funcion" es la función que se desea aplicar a cada elemento de la fila.

- el método `apply` también puede ser utilizado con funciones **lambda**, que son funciones anónimas y pequeñas que se definen dentro de una línea de código. Por ejemplo, si se quisiera aplicar una función **lambda** que tome como entrada una cadena de caracteres y devuelva la versión en mayúsculas de la misma, se podría utilizar el método apply de la siguiente manera:

```python
dataframe['nombre_columna'].apply(lambda x: x.upper())
```

<center>
<div>
<img src="img/lambda.png" width="200"/>
</div>

<div>
<img src="img/lambda1.png" width="200"/>
</div>
</center>

El método `apply` también puede aplicarse a múltiples columnas o filas utilizando la opción axis. Si `axis=0`, la función se aplicará a cada columna del dataframe. Si `axis=1`, la función se aplicará a cada fila del dataframe.

En resumen, el método `apply` se utiliza en Pandas para aplicar una función a una serie o dataframe, y puede utilizarse de diferentes maneras para aplicar la función.

In [307]:
data

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia López,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,1,Esteban Carvajal López,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,2,Elena Gómez López,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,3,Ana Tobón López,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,4,Julian Pardo López,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,5,Juan Lopez López,M,20.0,70,Rango 1: 18-24,NaN,7300.0

In [313]:
# Multiplicar x 2 todas las celdas
data.apply(lambda numero_x: numero_x*2)

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia LópezJose Urrutia López,MM,48.0,150,Rango 1: 18-24Rango 1: 18-24,NaN,17520.0
1,2,Esteban Carvajal LópezEsteban Carvajal López,MM,50.0,160,Rango 2: 25-32Rango 2: 25-32,NaN,18250.0
2,4,Elena Gómez LópezElena Gómez López,FF,64.0,120,Rango 2: 25-32Rango 2: 25-32,NaN,23360.0
3,6,Ana Tobón LópezAna Tobón López,FF,90.0,172,Rango 3: 33-54Rango 3: 33-54,NaN,32850.0
4,8,Julian Pardo LópezJulian Pardo López,MM,104.0,144,Rango 3: 33-54Rango 3: 33-54,NaN,37960.0
5,10,Juan Lopez LópezJuan Lopez López,MM,40.0,140,Rango 1: 18-24Rango 1: 18-24,NaN,14600.0

In [308]:
def multiplicar_x_2(x):
    return x*2

In [311]:
multiplicar_x_2(5)

10

In [309]:
data.apply(multiplicar_x_2)

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia LópezJose Urrutia López,MM,48.0,150,Rango 1: 18-24Rango 1: 18-24,NaN,17520.0
1,2,Esteban Carvajal LópezEsteban Carvajal López,MM,50.0,160,Rango 2: 25-32Rango 2: 25-32,NaN,18250.0
2,4,Elena Gómez LópezElena Gómez López,FF,64.0,120,Rango 2: 25-32Rango 2: 25-32,NaN,23360.0
3,6,Ana Tobón LópezAna Tobón López,FF,90.0,172,Rango 3: 33-54Rango 3: 33-54,NaN,32850.0
4,8,Julian Pardo LópezJulian Pardo López,MM,104.0,144,Rango 3: 33-54Rango 3: 33-54,NaN,37960.0
5,10,Juan Lopez LópezJuan Lopez López,MM,40.0,140,Rango 1: 18-24Rango 1: 18-24,NaN,14600.0

In [310]:
data

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia López,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,1,Esteban Carvajal López,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,2,Elena Gómez López,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,3,Ana Tobón López,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,4,Julian Pardo López,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,5,Juan Lopez López,M,20.0,70,Rango 1: 18-24,NaN,7300.0

In [315]:
# Convertir la edad de días a años
data["edad_dias"].apply(lambda x: x/365)

0    24.0
1    25.0
2    32.0
3    45.0
4    52.0
5    20.0
Name: edad_dias, dtype: float64

In [316]:
def funcion_ayuda(x):
    return x/365

In [ ]:
data.edad_dias.apply(funcion_ayuda)

0    24.0
1    25.0
2    32.0
3    45.0
4    52.0
5    20.0
Name: edad_dias, dtype: float64

In [317]:
data

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia López,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,1,Esteban Carvajal López,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,2,Elena Gómez López,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,3,Ana Tobón López,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,4,Julian Pardo López,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,5,Juan Lopez López,M,20.0,70,Rango 1: 18-24,NaN,7300.0

In [318]:
data[['edad','peso']].apply(np.mean)

edad    33.000000
peso    73.833333
dtype: float64

In [319]:
data[['edad','peso']].max()

edad    52.0
peso    86.0
dtype: float64

In [320]:
data[['edad','peso']].mean()

edad    33.000000
peso    73.833333
dtype: float64

### Eliminar filas y columnas

In [321]:
data

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia López,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,1,Esteban Carvajal López,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,2,Elena Gómez López,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,3,Ana Tobón López,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,4,Julian Pardo López,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,5,Juan Lopez López,M,20.0,70,Rango 1: 18-24,NaN,7300.0

In [323]:
data

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia López,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,1,Esteban Carvajal López,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,2,Elena Gómez López,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,3,Ana Tobón López,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,4,Julian Pardo López,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,5,Juan Lopez López,M,20.0,70,Rango 1: 18-24,NaN,7300.0

In [322]:
# Borre la fila identificada como 1
data.drop(1)

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia López,M,24.0,75,Rango 1: 18-24,NaN,8760.0
2,2,Elena Gómez López,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,3,Ana Tobón López,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,4,Julian Pardo López,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,5,Juan Lopez López,M,20.0,70,Rango 1: 18-24,NaN,7300.0

In [324]:
# Borre la columna nueva_variable y nueva_variable2
data.drop(columns = ["index", "nueva_variable2"], inplace = True)

In [325]:
data

                  nombres sexo  edad  peso  nueva_variable  edad_dias
0      Jose Urrutia López    M  24.0    75  Rango 1: 18-24     8760.0
1  Esteban Carvajal López    M  25.0    80  Rango 2: 25-32     9125.0
2       Elena Gómez López    F  32.0    60  Rango 2: 25-32    11680.0
3         Ana Tobón López    F  45.0    86  Rango 3: 33-54    16425.0
4      Julian Pardo López    M  52.0    72  Rango 3: 33-54    18980.0
5        Juan Lopez López    M  20.0    70  Rango 1: 18-24     7300.0

In [329]:
# Creemos un valor faltante
data.loc[0, "nombres"] = np.nan
data.loc[2, "peso"] = np.nan

In [330]:
data

                  nombres sexo  edad  peso  nueva_variable  edad_dias
0                     NaN    M  24.0  75.0  Rango 1: 18-24     8760.0
1  Esteban Carvajal López    M  25.0  80.0  Rango 2: 25-32     9125.0
2       Elena Gómez López    F  32.0   NaN  Rango 2: 25-32    11680.0
3         Ana Tobón López    F  45.0  86.0  Rango 3: 33-54    16425.0
4      Julian Pardo López    M  52.0  72.0  Rango 3: 33-54    18980.0
5        Juan Lopez López    M  20.0  70.0  Rango 1: 18-24     7300.0

In [331]:
# Eliminamos las filas con valores faltantes
data.dropna()

                  nombres sexo  edad  peso  nueva_variable  edad_dias
1  Esteban Carvajal López    M  25.0  80.0  Rango 2: 25-32     9125.0
3         Ana Tobón López    F  45.0  86.0  Rango 3: 33-54    16425.0
4      Julian Pardo López    M  52.0  72.0  Rango 3: 33-54    18980.0
5        Juan Lopez López    M  20.0  70.0  Rango 1: 18-24     7300.0

In [332]:
data.dropna(subset=['peso'])

                  nombres sexo  edad  peso  nueva_variable  edad_dias
0                     NaN    M  24.0  75.0  Rango 1: 18-24     8760.0
1  Esteban Carvajal López    M  25.0  80.0  Rango 2: 25-32     9125.0
3         Ana Tobón López    F  45.0  86.0  Rango 3: 33-54    16425.0
4      Julian Pardo López    M  52.0  72.0  Rango 3: 33-54    18980.0
5        Juan Lopez López    M  20.0  70.0  Rango 1: 18-24     7300.0

In [334]:
data.count()

nombres           5
sexo              6
edad              6
peso              5
nueva_variable    6
edad_dias         6
dtype: int64

In [333]:
data.isna().sum()

nombres           1
sexo              0
edad              0
peso              1
nueva_variable    0
edad_dias         0
dtype: int64

In [335]:
data.isna().mean()

nombres           0.166667
sexo              0.000000
edad              0.000000
peso              0.166667
nueva_variable    0.000000
edad_dias         0.000000
dtype: float64

La función `pd.concat` en Pandas se utiliza para concatenar dos o más objetos de Pandas a lo largo de un eje específico. Los objetos de Pandas pueden ser dataframes o series. La concatenación implica unir los objetos uno al lado del otro o uno debajo del otro, dependiendo del eje especificado.

La sintaxis básica de `pd.concat` es la siguiente:
```python
pd.concat(objetos, axis = 0, join = 'outer', ignore_index = False)
```
Donde:

- `objetos`: es una lista o tupla de objetos de Pandas que se desea concatenar.
- `axis`: especifica el eje a lo largo del cual se realizará la concatenación. Si `axis=0`, se concatenarán los objetos uno debajo del otro (verticalmente). Si `axis=1`, se concatenarán los objetos uno al lado del otro (horizontalmente).
- `join`: especifica el tipo de unión que se desea realizar. Puede ser `'inner'` (intersección de los índices), `'outer'` (unión de los índices) o `'left'` (unión de los índices del objeto en el lado izquierdo).
- `ignore_index`: especifica si se deben ignorar los índices originales y crear nuevos índices. Si es `True`, se crearán nuevos índices.

La función `pd.concat` **es muy útil para combinar dataframes o series que tienen columnas o índices en común**. Por ejemplo, si se tienen dos dataframes que comparten las mismas columnas y se desea combinarlos verticalmente, se podría utilizar el siguiente código:

In [353]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df1

   A  B
0  1  3
1  2  4

In [354]:
df2 = pd.DataFrame({'B': [5, 6], 'A': [7, 8]})
df2

   B  A
0  5  7
1  6  8

In [355]:
nuevo_df = pd.concat([df1, df2], axis=0)
nuevo_df.reset_index(drop=True)

   A  B
0  1  3
1  2  4
2  7  5
3  8  6

En este caso, se utilizará `axis=0` para concatenar los dataframes verticalmente. Los índices de los dataframes originales se conservarán en el nuevo dataframe.

La función `pd.concat` también puede ser utilizada para combinar dataframes o series que no tienen columnas o índices en común. En este caso, las columnas o índices faltantes se rellenarán con valores nulos. Por ejemplo, si se quisiera combinar horizontalmente dos dataframes que tienen diferentes columnas, se podría utilizar el siguiente código:

In [350]:
df1 = pd.DataFrame({'Edad': [10, 20], 'Peso': [30, 40]})
df1

   Edad  Peso
0    10    30
1    20    40

In [351]:
df2 = pd.DataFrame({'Número de hermanos': [5, 6], 'Escolaridad': ["primaria", "Bachillerato"]})
df2

   Número de hermanos   Escolaridad
0                   5      primaria
1                   6  Bachillerato

In [352]:
nuevo_df = pd.concat([df1, df2], axis=1) ### OJO
nuevo_df

   Edad  Peso  Número de hermanos   Escolaridad
0    10    30                   5      primaria
1    20    40                   6  Bachillerato

En este caso, se utilizará `axis=1` para concatenar los dataframes horizontalmente. Como los dataframes no tienen columnas en común, se crearán nuevas columnas con valores nulos.

En resumen, la función `pd.concat` en Pandas es una herramienta muy útil para combinar dataframes o series a lo largo de un eje específico. Se puede utilizar con diferentes parámetros para personalizar la unión de los objetos y crear un nuevo dataframe o serie.

In [356]:
data

                  nombres sexo  edad  peso  nueva_variable  edad_dias
0                     NaN    M  24.0  75.0  Rango 1: 18-24     8760.0
1  Esteban Carvajal López    M  25.0  80.0  Rango 2: 25-32     9125.0
2       Elena Gómez López    F  32.0   NaN  Rango 2: 25-32    11680.0
3         Ana Tobón López    F  45.0  86.0  Rango 3: 33-54    16425.0
4      Julian Pardo López    M  52.0  72.0  Rango 3: 33-54    18980.0
5        Juan Lopez López    M  20.0  70.0  Rango 1: 18-24     7300.0

In [357]:
# Creemos una nueva fila
nueva_fila = pd.DataFrame({"nombres": "Andrea Saldarriaga", "sexo": "F", "edad": 32, "peso": 60,'nueva_variable':'Rango 2: 25-32','edad_dias':12000}, index = [0])

In [358]:
nueva_fila

              nombres sexo  edad  peso  nueva_variable  edad_dias
0  Andrea Saldarriaga    F    32    60  Rango 2: 25-32      12000

In [359]:
data = pd.concat((data, nueva_fila), axis = 0)
data

                  nombres sexo  edad  peso  nueva_variable  edad_dias
0                     NaN    M  24.0  75.0  Rango 1: 18-24     8760.0
1  Esteban Carvajal López    M  25.0  80.0  Rango 2: 25-32     9125.0
2       Elena Gómez López    F  32.0   NaN  Rango 2: 25-32    11680.0
3         Ana Tobón López    F  45.0  86.0  Rango 3: 33-54    16425.0
4      Julian Pardo López    M  52.0  72.0  Rango 3: 33-54    18980.0
5        Juan Lopez López    M  20.0  70.0  Rango 1: 18-24     7300.0
0      Andrea Saldarriaga    F  32.0  60.0  Rango 2: 25-32    12000.0

In [366]:
# Creemos una fila duplicada
data = pd.concat((data, data.iloc[1:2,]), axis = 0)

In [367]:
data

                  nombres sexo  edad  peso  nueva_variable  edad_dias
0                     NaN    M  24.0  75.0  Rango 1: 18-24     8760.0
1  Esteban Carvajal López    M  25.0  80.0  Rango 2: 25-32     9125.0
2       Elena Gómez López    F  32.0   NaN  Rango 2: 25-32    11680.0
3         Ana Tobón López    F  45.0  86.0  Rango 3: 33-54    16425.0
4      Julian Pardo López    M  52.0  72.0  Rango 3: 33-54    18980.0
5        Juan Lopez López    M  20.0  70.0  Rango 1: 18-24     7300.0
0      Andrea Saldarriaga    F  32.0  60.0  Rango 2: 25-32    12000.0
1  Esteban Carvajal López    M  25.0  80.0  Rango 2: 25-32     9125.0

In [370]:
data.loc[data.duplicated(subset="nombres")]

                  nombres sexo  edad  peso  nueva_variable  edad_dias
1  Esteban Carvajal López    M  25.0  80.0  Rango 2: 25-32     9125.0

In [371]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
0    False
1     True
dtype: bool

In [372]:
# Eliminemos duplicados. Conserva la primera observación
data = data.drop_duplicates()
data

                  nombres sexo  edad  peso  nueva_variable  edad_dias
0                     NaN    M  24.0  75.0  Rango 1: 18-24     8760.0
1  Esteban Carvajal López    M  25.0  80.0  Rango 2: 25-32     9125.0
2       Elena Gómez López    F  32.0   NaN  Rango 2: 25-32    11680.0
3         Ana Tobón López    F  45.0  86.0  Rango 3: 33-54    16425.0
4      Julian Pardo López    M  52.0  72.0  Rango 3: 33-54    18980.0
5        Juan Lopez López    M  20.0  70.0  Rango 1: 18-24     7300.0
0      Andrea Saldarriaga    F  32.0  60.0  Rango 2: 25-32    12000.0

In [373]:
data.reset_index(drop=True,inplace=True)
data

                  nombres sexo  edad  peso  nueva_variable  edad_dias
0                     NaN    M  24.0  75.0  Rango 1: 18-24     8760.0
1  Esteban Carvajal López    M  25.0  80.0  Rango 2: 25-32     9125.0
2       Elena Gómez López    F  32.0   NaN  Rango 2: 25-32    11680.0
3         Ana Tobón López    F  45.0  86.0  Rango 3: 33-54    16425.0
4      Julian Pardo López    M  52.0  72.0  Rango 3: 33-54    18980.0
5        Juan Lopez López    M  20.0  70.0  Rango 1: 18-24     7300.0
6      Andrea Saldarriaga    F  32.0  60.0  Rango 2: 25-32    12000.0

In [374]:
data2 = pd.DataFrame({'direccion':['Cra 14','Calle 3','Carrera 4','Calle 72','Carrera 24','Calle 127']})

In [375]:
data2

    direccion
0      Cra 14
1     Calle 3
2   Carrera 4
3    Calle 72
4  Carrera 24
5   Calle 127

In [ ]:
pd.concat([data,data2],axis=1) ###ADVERTENCIA

,nombres,sexo,edad,peso,nueva_variable,edad_dias,direccion
0,NaN,M,24.0,75.0,Rango 1: 18-24,8760.0,Cra 14
1,Esteban Carvajal López,M,25.0,80.0,Rango 2: 25-32,9125.0,Calle 3
2,Elena Gómez López,F,32.0,NaN,Rango 2: 25-32,11680.0,Carrera 4
3,Ana Tobón López,F,45.0,86.0,Rango 3: 33-54,16425.0,Calle 72
4,Julian Pardo López,M,52.0,72.0,Rango 3: 33-54,18980.0,Carrera 24
5,Juan Lopez López,M,20.0,70.0,Rango 1: 18-24,7300.0,Calle 127
6,Andrea Saldarriaga,F,32.0,60.0,Rango 2: 25-32,12000.0,NaN

In [377]:
data.drop_duplicates(subset='sexo')

             nombres sexo  edad  peso  nueva_variable  edad_dias
0                NaN    M  24.0  75.0  Rango 1: 18-24     8760.0
2  Elena Gómez López    F  32.0   NaN  Rango 2: 25-32    11680.0

In [378]:
data

                  nombres sexo  edad  peso  nueva_variable  edad_dias
0                     NaN    M  24.0  75.0  Rango 1: 18-24     8760.0
1  Esteban Carvajal López    M  25.0  80.0  Rango 2: 25-32     9125.0
2       Elena Gómez López    F  32.0   NaN  Rango 2: 25-32    11680.0
3         Ana Tobón López    F  45.0  86.0  Rango 3: 33-54    16425.0
4      Julian Pardo López    M  52.0  72.0  Rango 3: 33-54    18980.0
5        Juan Lopez López    M  20.0  70.0  Rango 1: 18-24     7300.0
6      Andrea Saldarriaga    F  32.0  60.0  Rango 2: 25-32    12000.0

In [379]:
data2

    direccion
0      Cra 14
1     Calle 3
2   Carrera 4
3    Calle 72
4  Carrera 24
5   Calle 127

In [380]:
pd.concat([data,data2],axis=1)

,nombres,sexo,edad,peso,nueva_variable,edad_dias,direccion
0,NaN,M,24.0,75.0,Rango 1: 18-24,8760.0,Cra 14
1,Esteban Carvajal López,M,25.0,80.0,Rango 2: 25-32,9125.0,Calle 3
2,Elena Gómez López,F,32.0,NaN,Rango 2: 25-32,11680.0,Carrera 4
3,Ana Tobón López,F,45.0,86.0,Rango 3: 33-54,16425.0,Calle 72
4,Julian Pardo López,M,52.0,72.0,Rango 3: 33-54,18980.0,Carrera 24
5,Juan Lopez López,M,20.0,70.0,Rango 1: 18-24,7300.0,Calle 127
6,Andrea Saldarriaga,F,32.0,60.0,Rango 2: 25-32,12000.0,NaN

## Ejercicio 1

Para el siguiente ejercicio, usted importará el archivo `consumo_masivo_col.xslx`. Este dataset contiene los productos disponibles en los dos supermercados más grandes de Colombia, en el se incluye la marca, producto, precio en diferentes puntos de corte durante el año 2019. Primero, una introducción a como leer este archivo.

In [ ]:
!pip3 install openpyxl

Requirement already satisfied: openpyxl in c:\users\santiago neira\appdata\local\programs\python\python311\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\santiago neira\appdata\local\programs\python\python311\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [381]:
#ruta_archivo = '/content/consumo_masivo_col.xlsx' #Para GoogleColab
ruta_archivo = './datos/consumo_masivo_col.xlsx' #Para local
productos_consumo_masivo = pd.read_excel(ruta_archivo)

In [382]:
productos_consumo_masivo.head()

,date,prod_id,prod_name,prod_name_long,prod_brand,category,subcategory,tags,prod_unit_price,prod_units,prod_icon,prod_source,source_type
0,20190609,7702155021451,Limpia tapicería en espuma Binner,Limpia tapicería en espuma Binner x 400ml,BINNER,Supermercado,Aseo de hogar,Alfombras,15590,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1
1,20190609,7702155016457,Limpia tapicería y alfombras Binner,Limpia tapicería y alfombras Binner x 500ml,BINNER,Supermercado,Aseo de hogar,Alfombras,13993,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1
2,20190609,4008455446318,Limpiador Dr. Beckmann alfombras 2en1 poder oxi,Limpiador Dr. Beckmann alfombras 2en1 poder ox...,DR.BECKMANN,Supermercado,Aseo de hogar,Alfombras,16513,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1
3,20190609,7702532312677,Aceite Bon Aire eléctrico perfume flores,Aceite Bon Aire eléctrico perfume flores x 25 ml,BONAIRE,Supermercado,Aseo de hogar,Ambientadores,14990,Unidades,../icons/SVG/58-beauty-spas/spa-vapor.svg,VERDE,1
4,20190609,7702532312967,Ambientador Aire Varitas Bambú Bonaire 2 Repue...,Ambientador Aire Varitas Bambú Bonaire 2 Repue...,BONAIRE,Supermercado,Aseo de hogar,Ambientadores,34990,Unidades,../icons/SVG/58-beauty-spas/spa-vapor.svg,VERDE,1

In [ ]:
ruta_archivo= r"C:\Users\Santiago Neira\OneDrive - Universidad de los andes\Escritorio\Intro_analisis_datos_EDCO\clase_3\datos\consumo_masivo_col.xlsx"
productos_consumo_masivo = pd.read_excel(ruta_archivo)

In [ ]:
productos_consumo_masivo.head()

,date,prod_id,prod_name,prod_name_long,prod_brand,category,subcategory,tags,prod_unit_price,prod_units,prod_icon,prod_source,source_type
0,20190609,7702155021451,Limpia tapicería en espuma Binner,Limpia tapicería en espuma Binner x 400ml,BINNER,Supermercado,Aseo de hogar,Alfombras,15590,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1
1,20190609,7702155016457,Limpia tapicería y alfombras Binner,Limpia tapicería y alfombras Binner x 500ml,BINNER,Supermercado,Aseo de hogar,Alfombras,13993,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1
2,20190609,4008455446318,Limpiador Dr. Beckmann alfombras 2en1 poder oxi,Limpiador Dr. Beckmann alfombras 2en1 poder ox...,DR.BECKMANN,Supermercado,Aseo de hogar,Alfombras,16513,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1
3,20190609,7702532312677,Aceite Bon Aire eléctrico perfume flores,Aceite Bon Aire eléctrico perfume flores x 25 ml,BONAIRE,Supermercado,Aseo de hogar,Ambientadores,14990,Unidades,../icons/SVG/58-beauty-spas/spa-vapor.svg,VERDE,1
4,20190609,7702532312967,Ambientador Aire Varitas Bambú Bonaire 2 Repue...,Ambientador Aire Varitas Bambú Bonaire 2 Repue...,BONAIRE,Supermercado,Aseo de hogar,Ambientadores,34990,Unidades,../icons/SVG/58-beauty-spas/spa-vapor.svg,VERDE,1

#### Accediendo a los archivos a través del paquete os

In [ ]:
import os
os.getcwd()
os.chdir(r"C:\Users\Santiago Neira\OneDrive - Universidad de los andes\Escritorio\Intro_analisis_datos_EDCO\clase_3\datos")
os.getcwd()

'C:\\Users\\Santiago Neira\\OneDrive - Universidad de los andes\\Escritorio\\Intro_analisis_datos_EDCO\\clase_3\\datos'

In [ ]:
productos_consumo_masivo = pd.read_excel('consumo_masivo_col.xlsx')

In [383]:
productos_consumo_masivo.head()

,date,prod_id,prod_name,prod_name_long,prod_brand,category,subcategory,tags,prod_unit_price,prod_units,prod_icon,prod_source,source_type
0,20190609,7702155021451,Limpia tapicería en espuma Binner,Limpia tapicería en espuma Binner x 400ml,BINNER,Supermercado,Aseo de hogar,Alfombras,15590,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1
1,20190609,7702155016457,Limpia tapicería y alfombras Binner,Limpia tapicería y alfombras Binner x 500ml,BINNER,Supermercado,Aseo de hogar,Alfombras,13993,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1
2,20190609,4008455446318,Limpiador Dr. Beckmann alfombras 2en1 poder oxi,Limpiador Dr. Beckmann alfombras 2en1 poder ox...,DR.BECKMANN,Supermercado,Aseo de hogar,Alfombras,16513,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1
3,20190609,7702532312677,Aceite Bon Aire eléctrico perfume flores,Aceite Bon Aire eléctrico perfume flores x 25 ml,BONAIRE,Supermercado,Aseo de hogar,Ambientadores,14990,Unidades,../icons/SVG/58-beauty-spas/spa-vapor.svg,VERDE,1
4,20190609,7702532312967,Ambientador Aire Varitas Bambú Bonaire 2 Repue...,Ambientador Aire Varitas Bambú Bonaire 2 Repue...,BONAIRE,Supermercado,Aseo de hogar,Ambientadores,34990,Unidades,../icons/SVG/58-beauty-spas/spa-vapor.svg,VERDE,1

In [384]:
productos_consumo_masivo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25638 entries, 0 to 25637
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             25638 non-null  int64
 1   prod_id          25638 non-null  int64
 2   prod_name        25506 non-null  object
 3   prod_name_long   25638 non-null  object
 4   prod_brand       25586 non-null  object
 5   category         25638 non-null  object
 6   subcategory      25638 non-null  object
 7   tags             25638 non-null  object
 8   prod_unit_price  25633 non-null  object
 9   prod_units       25231 non-null  object
 10  prod_icon        25231 non-null  object
 11  prod_source      25638 non-null  object
 12  source_type      25638 non-null  int64
dtypes: int64(3), object(10)
memory usage: 2.5+ MB

In [385]:
productos_consumo_masivo.describe()

               date       prod_id  source_type
count  2.563800e+04  2.563800e+04      25638.0
mean   2.019279e+07  7.137052e+12          1.0
std    3.867261e+03  1.872051e+12          0.0
min    2.019061e+07  5.244812e+06          1.0
25%    2.019061e+07  7.702010e+12          1.0
50%    2.019071e+07  7.702177e+12          1.0
75%    2.019110e+07  7.703616e+12          1.0
max    2.020022e+07  9.333527e+12          1.0

### Trabajando con fechas al importar un archivo de excel

In [ ]:
productos_consumo_masivo['date'].head()

0    20190609
1    20190609
2    20190609
3    20190609
4    20190609
Name: date, dtype: int64

In [386]:
productos_consumo_masivo['date'] = pd.to_datetime(productos_consumo_masivo['date'],format='%Y%m%d')

In [388]:
productos_consumo_masivo.head(2)

,date,prod_id,prod_name,prod_name_long,prod_brand,category,subcategory,tags,prod_unit_price,prod_units,prod_icon,prod_source,source_type
0,2019-06-09,7702155021451,Limpia tapicería en espuma Binner,Limpia tapicería en espuma Binner x 400ml,BINNER,Supermercado,Aseo de hogar,Alfombras,15590,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1
1,2019-06-09,7702155016457,Limpia tapicería y alfombras Binner,Limpia tapicería y alfombras Binner x 500ml,BINNER,Supermercado,Aseo de hogar,Alfombras,13993,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1

### Trabajando con valores numéricos al importar un archivo de excel

In [389]:
productos_consumo_masivo.columns

Index(['date', 'prod_id', 'prod_name', 'prod_name_long', 'prod_brand',
       'category', 'subcategory', 'tags', 'prod_unit_price', 'prod_units',
       'prod_icon', 'prod_source', 'source_type'],
      dtype='object')

In [390]:
productos_consumo_masivo['prod_unit_price'].head()

0    15590
1    13993
2    16513
3    14990
4    34990
Name: prod_unit_price, dtype: object

In [391]:
productos_consumo_masivo['prod_unit_price'].dtype

dtype('O')

In [392]:
productos_consumo_masivo['prod_unit_price'].astype(float)

ValueError: could not convert string to float: '70386,95'

In [393]:
productos_consumo_masivo['prod_unit_price'] = pd.to_numeric(productos_consumo_masivo['prod_unit_price'].astype(str).str.replace(',', '.'),errors='coerce')

In [394]:
productos_consumo_masivo.head()

,date,prod_id,prod_name,prod_name_long,prod_brand,category,subcategory,tags,prod_unit_price,prod_units,prod_icon,prod_source,source_type
0,2019-06-09,7702155021451,Limpia tapicería en espuma Binner,Limpia tapicería en espuma Binner x 400ml,BINNER,Supermercado,Aseo de hogar,Alfombras,15590.0,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1
1,2019-06-09,7702155016457,Limpia tapicería y alfombras Binner,Limpia tapicería y alfombras Binner x 500ml,BINNER,Supermercado,Aseo de hogar,Alfombras,13993.0,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1
2,2019-06-09,4008455446318,Limpiador Dr. Beckmann alfombras 2en1 poder oxi,Limpiador Dr. Beckmann alfombras 2en1 poder ox...,DR.BECKMANN,Supermercado,Aseo de hogar,Alfombras,16513.0,Unidades,../icons/SVG/53-places/home-3.svg,VERDE,1
3,2019-06-09,7702532312677,Aceite Bon Aire eléctrico perfume flores,Aceite Bon Aire eléctrico perfume flores x 25 ml,BONAIRE,Supermercado,Aseo de hogar,Ambientadores,14990.0,Unidades,../icons/SVG/58-beauty-spas/spa-vapor.svg,VERDE,1
4,2019-06-09,7702532312967,Ambientador Aire Varitas Bambú Bonaire 2 Repue...,Ambientador Aire Varitas Bambú Bonaire 2 Repue...,BONAIRE,Supermercado,Aseo de hogar,Ambientadores,34990.0,Unidades,../icons/SVG/58-beauty-spas/spa-vapor.svg,VERDE,1

A partir del dataframe anterior, responda las siguientes preguntas:

1. Antes de iniciar, trate de familiarizarse un poco con la base de datos. ¿Cuántos valores de `subcategory` existen? ¿A qué corresponden? ¿Cuántos valores de `prod_units` existen? ¿A qué corresponden?
2. ¿Cuál es el rango de precios que se encuentra en esta base de datos?
3. ¿Cuál es el precio promedio de los artículos de cuidado personal?
4. ¿Cuáles son  las cinco `Galletas dulces` más costosas del mercado? ¿A qué marcas corresponden?
5. ¿Cuáles son las cinco marcas que tienen más productos por debajo de los $10,000 pesos? ¿Cuáles son? Encuentre algunos ejemplos de estos productos.
7. ¿Cuántos productos tienen como fecha Febrero de 2020? ¿Cuáles son las dos marcas con más productos en esta fecha?

In [395]:
productos_consumo_masivo.columns

Index(['date', 'prod_id', 'prod_name', 'prod_name_long', 'prod_brand',
       'category', 'subcategory', 'tags', 'prod_unit_price', 'prod_units',
       'prod_icon', 'prod_source', 'source_type'],
      dtype='object')

In [396]:
## 1. Valores únicos de subcategory
productos_consumo_masivo['subcategory'].unique()

array(['Aseo de hogar', 'Bebidas', 'Belleza', 'Charcutería',
       'Cuidado de ropa y calzado', 'Cuidado Personal', 'Despensa',
       'Dulces y postres', 'Lácteos, huevos y refrigerados',
       'Limpieza de cocina', 'Panadería y Pastelería', 'Pasabocas',
       'Productos Congelados', 'Vinos y Licores'], dtype=object)

In [397]:
## Número de elementos únicos en subcategory
productos_consumo_masivo['subcategory'].nunique()

14

In [398]:
productos_consumo_masivo['prod_units'].unique()

array(['Unidades', 'Botella', nan], dtype=object)

In [399]:
productos_consumo_masivo['prod_units'].nunique()

2

In [400]:
###2. Rango de precios de la base de datos
productos_consumo_masivo['prod_unit_price'].describe()

count     25633.000000
mean      16180.033485
std       39862.123156
min           0.000000
25%        4190.000000
50%        7390.000000
75%       13990.000000
max      990000.000000
Name: prod_unit_price, dtype: float64

In [401]:
print(productos_consumo_masivo['prod_unit_price'].min())
print(productos_consumo_masivo['prod_unit_price'].max())

0.0
990000.0

In [411]:
productos_consumo_masivo.shape

(25638, 13)

In [412]:
### Precio promedio de los artículos de cuidado personal
base_cuidado_personal = productos_consumo_masivo.loc[productos_consumo_masivo['subcategory']=='Cuidado Personal']
base_cuidado_personal['prod_unit_price'].mean()

np.float64(11360.566067240032)

In [416]:
#¿Cuáles son  las cinco `Galletas dulces` más costosas del mercado? ¿A qué marcas corresponden?
productos_consumo_masivo['tags'].unique()

array(['Alfombras', 'Ambientadores', 'Blanqueadores', 'Cera',
       'Desinfectantes', 'Insecticidas', 'Limpieza de superficies',
       'Limpieza W.C.', 'Multiusos', 'Agua', 'Energizantes', 'Gaseosas',
       'Hidratantes', 'Jugos, refrescos y maltas', 'Té líquido',
       'Accesorios de belleza', 'Coloración', 'Cremas corporales',
       'Cuidado Facial', 'Depilación', 'Maquillaje', 'Protección solar',
       'Repelentes', 'Carnes frías maduradas y ahumadas',
       'Encurtidos y otros', 'Quesos especializados', 'Betún',
       'Desmanchadores', 'Detergentes', 'Jabones de Barra',
       'Prelavado y preplanchado', 'Suavizantes',
       'Acondicionadores y tratamientos', 'Afeitado', 'Botiquín',
       'Cuidado de pies', 'Cuidado Oral', 'Desodorantes',
       'Gel y Fijadores', 'Jabones de tocador', 'Pañuelos',
       'Papel higiénico', 'Protección Adulta', 'Protección Femenina',
       'Shampoo', 'Aceite', 'Arroz y granos', 'Avenas y salvado',
       'Azúcar, Endulzantes y Panelas', 'Bases, cremas y sopas',
       'Bebida achocolatada en polvo', 'Café', 'Cereales',
       'Chocolate de mesa', 'Condimentos, caldos y sal',
       'Enlatados y conservas', 'Harinas y mezclas para preparar',
       'Pastas', 'Salsas y vinagres', 'Té, infusiones e instantáneos',
       'Arequipe', 'Chocolatería', 'Confitería',
       'Crema leche y leche condensada', 'Dulces típicos',
       'Gelatinas, flanes y pudines', 'Repostería', 'Arepas', 'Avena',
       'Carnes frías y embutidos', 'Huevos', 'Kumis', 'Leche',
       'Leches vegetales', 'Mantequilla', 'Margarina',
       'Postres refrigerados', 'Queso', 'Tamales', 'Waffles y Crepes',
       'Yogurt', 'Baldes, escobas y accesorios', 'Bolsas de basura',
       'Esponjas y fibras', 'Guantes', 'Lavalozas',
       'Servilletas y papel aluminio', 'Antojos', 'Panadería Artesanal',
       'Panadería empacada', 'Pastelería', 'Frutos Secos',
       'Galletas dietéticas y saludables', 'Galletas dulces',
       'Galletas saladas', 'Mermelada y Cremas de untar',
       'Papas fritas y paquetes', 'Pasabocas para microondas', 'Apanados',
       'Empanadas', 'Helados', 'Masas y snacks',
       'Papas, yucas y patacones', 'Pizza y pastas congeladas',
       'Verduras Congeladas', 'Aguardiente', 'Aperitivos', 'Brandy',
       'Cervezas', 'Champañas y espumoso', 'Cognac', 'Ginebra', 'Ron',
       'Tequilas y piscos', 'Vino', 'Vodka', 'Whisky'], dtype=object)

In [419]:
dulces=productos_consumo_masivo.loc[productos_consumo_masivo['subcategory']=='Dulces y postres']
dulces['tags'].unique()

array(['Arequipe', 'Chocolatería', 'Confitería',
       'Crema leche y leche condensada', 'Dulces típicos',
       'Gelatinas, flanes y pudines', 'Repostería'], dtype=object)

In [422]:
'Galletas dulces' in productos_consumo_masivo['tags'].values

True

In [ ]:
productos_galletas= productos_consumo_masivo.loc[productos_consumo_masivo['tags']=='Galletas dulces']
productos_galletas.sort_values('prod_unit_price', ascending=False).head(10)

,date,prod_id,prod_name,prod_name_long,prod_brand,category,subcategory,tags,prod_unit_price,prod_units,prod_icon,prod_source,source_type
5399,2019-06-09,7591675010508,Barquilla Pirulin chocolate avellanas,Barquilla Pirulin chocolate avellanas x 300 g,PIRULIN,Supermercado,Pasabocas,Galletas dulces,21590.0,Unidades,../icons/SVG/74-food/cookie.svg,VERDE,1
19157,2019-11-01,7591675010508,Barquilla Pirulin chocolate avellanas,Barquilla Pirulin chocolate avellanas x 300 g,PIRULIN,Supermercado,Pasabocas,Galletas dulces,21590.0,Unidades,../icons/SVG/74-food/cookie.svg,VERDE,1
13432,2019-07-09,7591675010508,Barquilla Pirulin chocolate avellanas,Barquilla Pirulin chocolate avellanas x 300 g,PIRULIN,Supermercado,Pasabocas,Galletas dulces,21590.0,Unidades,../icons/SVG/74-food/cookie.svg,VERDE,1
6928,2019-07-09,7466762939010,Barquilla chocolate avellanas Pirulin,Barquilla Chocolate av,PIRULIN,Supermercado,Pasabocas,Galletas dulces,16100.0,Unidades,../icons/SVG/74-food/cookie.svg,AMARILLO,1
5377,2019-06-09,8000350001186,Galletas Mini Voglie Vicenzi Bl,Galletas Mini Voglie Vicenzi Bl x300g,VICENZI,Supermercado,Pasabocas,Galletas dulces,15590.0,Unidades,../icons/SVG/74-food/cookie.svg,VERDE,1
13410,2019-07-09,8000350001186,Galletas Mini Voglie Vicenzi Bl,Galletas Mini Voglie Vicenzi Bl x300g,VICENZI,Supermercado,Pasabocas,Galletas dulces,15590.0,Unidades,../icons/SVG/74-food/cookie.svg,VERDE,1
19136,2019-11-01,8000350001186,Galletas Mini Voglie Vicenzi Bl,Galletas Mini Voglie Vicenzi Bl x300g,VICENZI,Supermercado,Pasabocas,Galletas dulces,15590.0,Unidades,../icons/SVG/74-food/cookie.svg,VERDE,1
5368,2019-06-09,4001518450017,Galletas Griesson Café Música,Galletas Griesson Café Música X 200g,GRIESSON,Supermercado,Pasabocas,Galletas dulces,14590.0,Unidades,../icons/SVG/74-food/cookie.svg,VERDE,1
19128,2019-11-01,4001518450017,Galletas Griesson Café Música,Galletas Griesson Café Música X 200g,GRIESSON,Supermercado,Pasabocas,Galletas dulces,14590.0,Unidades,../icons/SVG/74-food/cookie.svg,VERDE,1
13401,2019-07-09,4001518450017,Galletas Griesson Café Música,Galletas Griesson Café Música X 200g,GRIESSON,Supermercado,Pasabocas,Galletas dulces,14590.0,Unidades,../icons/SVG/74-food/cookie.svg,VERDE,1

In [426]:
##5. ¿Cuáles son las cinco marcas que tienen más productos por debajo de los $10,000 pesos? ¿Cuáles son? Encuentre algunos ejemplos de estos productos.
productos_bajo_10k= productos_consumo_masivo.loc[productos_consumo_masivo['prod_unit_price']<10000]
productos_bajo_10k.drop_duplicates(subset=['prod_id'])
productos_bajo_10k['prod_brand'].value_counts().head(5)

prod_brand
VOGUE      667
COLANTA    439
ALPINA     413
JUMBO      286
MASGLO     258
Name: count, dtype: int64

In [ ]:
productos_bajo_10k