# **Introducción al análisis de datos en Python** 
#### Profesor: Santiago Neira

## Clase 3. Pandas

Una de las habilidades más relevantes para un Data Analyst o un Data Scientist es el manejo de datos estructurados. En este tutorial aprenderá cómo importar archivos a Python para crear `DataFrames` y de esta forma manipularlos para que estos queden en el formato más conveniente para su análisis.

> **Objetivos de la sesión**: Al finalizar esta clase, usted podrá:
> - Crear DataFrames y explorar su estructura
> - Seleccionar y filtrar datos con `.loc`, `.iloc` y condiciones booleanas
> - Modificar valores y calcular estadísticas descriptivas
> - Importar archivos Excel y realizar limpieza básica de datos

## Introducción a Pandas

###  ¿Qué es Pandas?
Pandas es una librería de código abierto para Python que proporciona herramientas de análisis de datos de alto rendimiento y fáciles de usar. Está construida sobre la biblioteca NumPy y proporciona estructuras de datos de alto nivel para trabajar con datos estructurados y tabulares, como hojas de cálculo y bases de datos relacionales.

Algunas de las características más importantes de Pandas son:

- Ofrece estructuras de datos para trabajar con datos tabulares, como el DataFrame y la Serie.
- Proporciona herramientas para la lectura y escritura de datos desde y hacia una variedad de formatos de archivo, como CSV, Excel, SQL, entre otros.
- Permite realizar operaciones de limpieza y preprocesamiento de datos, como la eliminación de valores perdidos o la normalización de datos.
- Ofrece una amplia variedad de métodos para el análisis de datos, como el agrupamiento, la agregación, la selección y el filtrado de datos.
- Permite la visualización de datos con la integración con otras bibliotecas de Python, como Matplotlib.

Pandas es ampliamente utilizado en ciencia de datos, finanzas, ingeniería y otras disciplinas que requieren la manipulación y el análisis de grandes conjuntos de datos. Es una de las herramientas más populares en Python para el análisis de datos debido a su facilidad de uso y su amplia gama de funciones.

En el siguiente diagrama se puede ver la estructura general de un `dataframe`, es muy similar a un Excel pero solo con una hoja. En este caso las filas representan observaciones y las columnas representan variables.

<center>
<img src="img/dataframe.png" alt="dataframe" width="500" height="300">
</center>

Comenzaremos nuestra introducción a `Pandas` creando nuestro primer `dataframe` con un diccionario.

In [1]:
!pip3 install pandas

Requirement already satisfied: pandas in c:\users\santiago neira\appdata\local\programs\python\python311\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\santiago neira\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\santiago neira\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\santiago neira\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\santiago neira\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\santiago neira\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
#%pip3 install pandas

In [3]:
import pandas as pd

In [4]:
# Cada variable de nuestro dataframe partirá de una lista
nombres = ["Jose", "Esteban", "Elena", "Ana", "Julian", "Juan", "Maria", "Carlos", "Laura", "Pedro", "Sofia", "Andres"]
sexo = ["M", "M", "F", "F", "M", None, "F", "M", "F", "M", "F", "M"]
edad = [24, 25, 32, 45, 52, 20, 28, 38, 41, 19, 35, 29]
peso = [75, 80, 60, 86, 72, 70, 58, 90, 65, 68, 62, 78]

In [5]:
# Creamos un diccionario con toda la información
un_diccionario = {
    "nombres": nombres,
    "sexo": sexo,
    "edad": edad,
    "peso": peso
}

In [6]:
un_diccionario

{'nombres': ['Jose',
  'Esteban',
  'Elena',
  'Ana',
  'Julian',
  'Juan',
  'Maria',
  'Carlos',
  'Laura',
  'Pedro',
  'Sofia',
  'Andres'],
 'sexo': ['M', 'M', 'F', 'F', 'M', None, 'F', 'M', 'F', 'M', 'F', 'M'],
 'edad': [24, 25, 32, 45, 52, 20, 28, 38, 41, 19, 35, 29],
 'peso': [75, 80, 60, 86, 72, 70, 58, 90, 65, 68, 62, 78]}

In [7]:
# Construimos nuestro primer dataframe
data = pd.DataFrame(un_diccionario)

In [8]:
# Visualizamos nuestro dataframe
data

    nombres  sexo  edad  peso
0      Jose     M    24    75
1   Esteban     M    25    80
2     Elena     F    32    60
3       Ana     F    45    86
4    Julian     M    52    72
5      Juan  None    20    70
6     Maria     F    28    58
7    Carlos     M    38    90
8     Laura     F    41    65
9     Pedro     M    19    68
10    Sofia     F    35    62
11   Andres     M    29    78

El `dataframe` es un objeto en Python que tiene unos atributos especiales. Estos atributos nos sirven para estudiar las características de nuestro objeto. Los principales se listan a continuación: 

- `.index`: es una propiedad que devuelve una lista con los nombres de fila del dataframe.

- `.columns`: es una propiedad que devuelve una lista con los nombres de las columnas del dataframe.

- `.shape`: es una propiedad que devuelve una tupla que indica el número de filas y columnas en el dataframe. Por ejemplo, un dataframe con 100 filas y 5 columnas tendría una forma de (100, 5).

- `.size`: es una propiedad que devuelve la cantidad de datos o celdas del dataframe. Por ejemplo, un dataframe con 100 filas y 5 columnas tendría un `size` de $100\times5=500$.

- `.count()`: este método cuenta la cantidad de valores no nulos por columna o fila.

- `.values`: es una propiedad que devuelve un array NumPy que contiene los valores del dataframe.

- `.T`: es un atributo que devuelve la base traspuesta.

- `.dtypes`: es una propiedad que devuelve un objeto que describe los tipos de datos de cada columna.

- `.head(n)`: es un método que devuelve las primeras n filas del dataframe.

- `.tail(n)`: es un método que devuelve las últimas n filas del dataframe.

- `.info()`: es un método que muestra información sobre el dataframe, incluyendo su forma, los tipos de datos de cada columna y la cantidad de valores no nulos.

- `.describe()`: es un método que muestra estadísticas descriptivas sobre el dataframe, incluyendo la media, la mediana, la desviación estándar, etc.

A continuación estudiaremos a detalle cada uno de estos métodos y atributos.

In [9]:
data

    nombres  sexo  edad  peso
0      Jose     M    24    75
1   Esteban     M    25    80
2     Elena     F    32    60
3       Ana     F    45    86
4    Julian     M    52    72
5      Juan  None    20    70
6     Maria     F    28    58
7    Carlos     M    38    90
8     Laura     F    41    65
9     Pedro     M    19    68
10    Sofia     F    35    62
11   Andres     M    29    78

In [10]:
# .index Estudiamos los nombres del índice
data.index

RangeIndex(start=0, stop=12, step=1)

In [11]:
# .columns ¿Cuáles son los nombres de las columnas?
data.columns

Index(['nombres', 'sexo', 'edad', 'peso'], dtype='object')

In [12]:
# .shape ¿Cuáles son las dimensiones del dataframe?
data.shape

(12, 4)

### Dimensiones y estructura del DataFrame

Los atributos `.index`, `.columns`, `.shape` y `.size` nos permiten conocer la estructura básica de nuestros datos.

In [13]:
# .size ¿Cuántos datos tengo?
data.size

48

In [14]:
# .count() ¿Cuántos datos no nulos tengo por columna?
data.count()

nombres    12
sexo       11
edad       12
peso       12
dtype: int64

In [15]:
# .count() ¿Cuántos datos no nulos tengo por fila/observación/individuo?
data.count(axis = 1)

0     4
1     4
2     4
3     4
4     4
5     3
6     4
7     4
8     4
9     4
10    4
11    4
dtype: int64

In [16]:
# axis = 0 calcula las funciones por columna. Esta es la opción por default
# axis = 1 calcula las funciones por fila
data.count(axis = 0)

nombres    12
sexo       11
edad       12
peso       12
dtype: int64

In [17]:
# .values Convierte el dataframe en un np.array de dos dimensiones
data.values

array([['Jose', 'M', 24, 75],
       ['Esteban', 'M', 25, 80],
       ['Elena', 'F', 32, 60],
       ['Ana', 'F', 45, 86],
       ['Julian', 'M', 52, 72],
       ['Juan', None, 20, 70],
       ['Maria', 'F', 28, 58],
       ['Carlos', 'M', 38, 90],
       ['Laura', 'F', 41, 65],
       ['Pedro', 'M', 19, 68],
       ['Sofia', 'F', 35, 62],
       ['Andres', 'M', 29, 78]], dtype=object)

In [18]:
# .T Trasponer
data.T

,0,1,2,3,4,5,6,7,8,9,10,11
nombres,Jose,Esteban,Elena,Ana,Julian,Juan,Maria,Carlos,Laura,Pedro,Sofia,Andres
sexo,M,M,F,F,M,None,F,M,F,M,F,M
edad,24,25,32,45,52,20,28,38,41,19,35,29
peso,75,80,60,86,72,70,58,90,65,68,62,78

In [19]:
data_transpuesta = data.T

In [20]:
data.T.index

Index(['nombres', 'sexo', 'edad', 'peso'], dtype='object')

In [21]:
data.T.columns

RangeIndex(start=0, stop=12, step=1)

In [22]:
# .dtypes ¿Cuál es el tipo de cada variable?
data.dtypes

nombres    object
sexo       object
edad        int64
peso        int64
dtype: object

### Exploración rápida: head() y tail()

Los métodos `.head(n)` y `.tail(n)` permiten visualizar las primeras o últimas filas del DataFrame sin cargar todo el conjunto de datos.

In [23]:
# .head() por defecto entrega las primeras 5 filas
data.head()

   nombres sexo  edad  peso
0     Jose    M    24    75
1  Esteban    M    25    80
2    Elena    F    32    60
3      Ana    F    45    86
4   Julian    M    52    72

In [24]:
# Primera fila
data.head(1)

  nombres sexo  edad  peso
0    Jose    M    24    75

In [25]:
# Primeras dos filas
data.head(2)

   nombres sexo  edad  peso
0     Jose    M    24    75
1  Esteban    M    25    80

In [26]:
# .tail() Por defecto devuelve las últimas 5 filas
data.tail()

   nombres sexo  edad  peso
7   Carlos    M    38    90
8    Laura    F    41    65
9    Pedro    M    19    68
10   Sofia    F    35    62
11  Andres    M    29    78

In [27]:
# Última fila
data.tail(1)

   nombres sexo  edad  peso
11  Andres    M    29    78

In [28]:
# Últimas dos filas
data.tail(2)

   nombres sexo  edad  peso
10   Sofia    F    35    62
11  Andres    M    29    78

In [29]:
# .info() descripción general de la estructura de la base
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nombres  12 non-null     object
 1   sexo     11 non-null     object
 2   edad     12 non-null     int64
 3   peso     12 non-null     int64
dtypes: int64(2), object(2)
memory usage: 516.0+ bytes

### Resumen de la estructura: info() y describe()

Los métodos `.info()` y `.describe()` ofrecen una visión general del DataFrame: tipos de datos, valores no nulos y estadísticas descriptivas.

In [30]:
# .describe() Estadísticas descriptivas de la data
data.describe()

            edad       peso
count  12.000000  12.000000
mean   32.333333  72.000000
std    10.201010  10.171261
min    19.000000  58.000000
25%    24.750000  64.250000
50%    30.500000  71.000000
75%    38.750000  78.500000
max    52.000000  90.000000

In [31]:
data.describe(include = "object")

       nombres sexo
count       12   11
unique      12    2
top       Jose    M
freq         1    6

In [32]:
data.describe(include = "all")

       nombres sexo       edad       peso
count       12   11  12.000000  12.000000
unique      12    2        NaN        NaN
top       Jose    M        NaN        NaN
freq         1    6        NaN        NaN
mean       NaN  NaN  32.333333  72.000000
std        NaN  NaN  10.201010  10.171261
min        NaN  NaN  19.000000  58.000000
25%        NaN  NaN  24.750000  64.250000
50%        NaN  NaN  30.500000  71.000000
75%        NaN  NaN  38.750000  78.500000
max        NaN  NaN  52.000000  90.000000

### Indexación y ejes
Adicionalmente, para manipular los dataframes es importante aprender como extraer fracciones de nuestra información. A esto se le conoce generalmente como *slicing*. En esta sección aprenderemos a filtrar la data por columnas y por filas. Los métodos que veremos serán.

- `[{nombre de la columna}]` y `.{nombre de la columna}`: Extracción de columnas.

- `set_index()`: Convertir una columna como índice.

- `.loc[]`: es un método para acceder a filas y columnas del dataframe por etiquetas de fila y columna.

- `.iloc[]`: es un método para acceder a filas y columnas del dataframe por índice entero.

- `.groupby()`: es un método para agrupar los datos por una o más columnas y realizar cálculos sobre los grupos resultantes.

- `.reset_index()`: Reiniciar el índice para que sea una enumeración de las filas.

- `.sort_values()`: Re-ordenar las filas.

- `.rename()`: Cambiarle el nombre a una fila o una columna.

- `.unique()`: Devuelve los valores únicos de la columna.

- `.value_counts()`: Cuenta la cantidad de valores únicos por columna.

**Extraer columnas**

Para extraer columnas tenemos dos métodos.
1. El primero consiste escribir entre corchetes cuadrados (`[]`) el nombre de la columna que se desea extraer entre comillas. Este método también permite extraer más de una columnas. Si ese es el caso, se pondría entre los corchetes cuadrados una lista con los nombres de las columnas deseadas entre comillas y separadas por comas.
2. El segundo método consiste en poner el nombre de la columna que se quiere extraer después de un punto `.`. Este método solo sirve si el nombre no está separado por espacios o caracteres especiales.

In [33]:
data

    nombres  sexo  edad  peso
0      Jose     M    24    75
1   Esteban     M    25    80
2     Elena     F    32    60
3       Ana     F    45    86
4    Julian     M    52    72
5      Juan  None    20    70
6     Maria     F    28    58
7    Carlos     M    38    90
8     Laura     F    41    65
9     Pedro     M    19    68
10    Sofia     F    35    62
11   Andres     M    29    78

In [34]:
# Método 1
data["nombres"]

0        Jose
1     Esteban
2       Elena
3         Ana
4      Julian
5        Juan
6       Maria
7      Carlos
8       Laura
9       Pedro
10      Sofia
11     Andres
Name: nombres, dtype: object

In [35]:
# Método 1
data[["nombres", "peso"]]

    nombres  peso
0      Jose    75
1   Esteban    80
2     Elena    60
3       Ana    86
4    Julian    72
5      Juan    70
6     Maria    58
7    Carlos    90
8     Laura    65
9     Pedro    68
10    Sofia    62
11   Andres    78

In [36]:
columnas_deseadas = ['nombres', "peso"]
data[columnas_deseadas]

    nombres  peso
0      Jose    75
1   Esteban    80
2     Elena    60
3       Ana    86
4    Julian    72
5      Juan    70
6     Maria    58
7    Carlos    90
8     Laura    65
9     Pedro    68
10    Sofia    62
11   Andres    78

In [37]:
# Método 2
data.nombres

0        Jose
1     Esteban
2       Elena
3         Ana
4      Julian
5        Juan
6       Maria
7      Carlos
8       Laura
9       Pedro
10      Sofia
11     Andres
Name: nombres, dtype: object

In [38]:
data

    nombres  sexo  edad  peso
0      Jose     M    24    75
1   Esteban     M    25    80
2     Elena     F    32    60
3       Ana     F    45    86
4    Julian     M    52    72
5      Juan  None    20    70
6     Maria     F    28    58
7    Carlos     M    38    90
8     Laura     F    41    65
9     Pedro     M    19    68
10    Sofia     F    35    62
11   Andres     M    29    78

#### set_index() y reset_index()

Podemos usar una columna como índice del DataFrame con `set_index()`. El método `reset_index()` permite volver al índice numérico por defecto.

In [39]:
# Convertir una columna como un índice
data_con_indice_nombre = data.set_index('nombres')

In [40]:
data_con_indice_nombre.index

Index(['Jose', 'Esteban', 'Elena', 'Ana', 'Julian', 'Juan', 'Maria', 'Carlos',
       'Laura', 'Pedro', 'Sofia', 'Andres'],
      dtype='object', name='nombres')

In [41]:
data.set_index('nombres')

         sexo  edad  peso
nombres
Jose        M    24    75
Esteban     M    25    80
Elena       F    32    60
Ana         F    45    86
Julian      M    52    72
Juan     None    20    70
Maria       F    28    58
Carlos      M    38    90
Laura       F    41    65
Pedro       M    19    68
Sofia       F    35    62
Andres      M    29    78

In [42]:
data['peso']

0     75
1     80
2     60
3     86
4     72
5     70
6     58
7     90
8     65
9     68
10    62
11    78
Name: peso, dtype: int64

In [43]:
# Si no sobreescribimos el objeto, no se guardan los cambios
data = data.set_index('nombres')
data

         sexo  edad  peso
nombres
Jose        M    24    75
Esteban     M    25    80
Elena       F    32    60
Ana         F    45    86
Julian      M    52    72
Juan     None    20    70
Maria       F    28    58
Carlos      M    38    90
Laura       F    41    65
Pedro       M    19    68
Sofia       F    35    62
Andres      M    29    78

In [44]:
# Otra forma de sobreescribir el objeto sin necesidad de asignarlo es usando el argumento inplace = True, dentro
# de las funciones de Pandas
data.set_index("sexo", append = True, inplace = True)
data

              edad  peso
nombres sexo
Jose    M       24    75
Esteban M       25    80
Elena   F       32    60
Ana     F       45    86
Julian  M       52    72
Juan    NaN     20    70
Maria   F       28    58
Carlos  M       38    90
Laura   F       41    65
Pedro   M       19    68
Sofia   F       35    62
Andres  M       29    78

In [45]:
# Para resetar el índice usamos .reset_index()
data.reset_index(inplace = True)
data

    nombres sexo  edad  peso
0      Jose    M    24    75
1   Esteban    M    25    80
2     Elena    F    32    60
3       Ana    F    45    86
4    Julian    M    52    72
5      Juan  NaN    20    70
6     Maria    F    28    58
7    Carlos    M    38    90
8     Laura    F    41    65
9     Pedro    M    19    68
10    Sofia    F    35    62
11   Andres    M    29    78

In [46]:
# Vuelva nombres el índice
data.set_index("nombres", inplace = True)

In [47]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70
Maria      F    28    58
Carlos     M    38    90
Laura      F    41    65
Pedro      M    19    68
Sofia      F    35    62
Andres     M    29    78

In [48]:
# Ordene por edad de menor a mayor. No guarde el valor
data.sort_values(['sexo','peso'])

        sexo  edad  peso
nombres
Maria      F    28    58
Elena      F    32    60
Sofia      F    35    62
Laura      F    41    65
Ana        F    45    86
Pedro      M    19    68
Julian     M    52    72
Jose       M    24    75
Andres     M    29    78
Esteban    M    25    80
Carlos     M    38    90
Juan     NaN    20    70

#### Ordenamiento, renombrado y conteo de valores

A continuación veremos cómo ordenar filas con `sort_values()`, renombrar columnas con `rename()`, y obtener valores únicos o conteos con `unique()` y `value_counts()`.

In [49]:
# Ordene por edad de mayor a menor. No guarde el valor
data.sort_values('edad', ascending = False)

# Note que los índices se movieron!

        sexo  edad  peso
nombres
Julian     M    52    72
Ana        F    45    86
Laura      F    41    65
Carlos     M    38    90
Sofia      F    35    62
Elena      F    32    60
Andres     M    29    78
Maria      F    28    58
Esteban    M    25    80
Jose       M    24    75
Juan     NaN    20    70
Pedro      M    19    68

In [50]:
# Cambie el nombre de la columna sexo a género
data.rename(columns = {"sexo": "género"})

        género  edad  peso
nombres
Jose         M    24    75
Esteban      M    25    80
Elena        F    32    60
Ana          F    45    86
Julian       M    52    72
Juan       NaN    20    70
Maria        F    28    58
Carlos       M    38    90
Laura        F    41    65
Pedro        M    19    68
Sofia        F    35    62
Andres       M    29    78

In [51]:
# Valores únicos de la columna sexo
data.sexo.unique()

array(['M', 'F', nan], dtype=object)

In [52]:
# ¿Cuántos hombres y mujeres tenemos?
data["sexo"].value_counts(dropna=False)

sexo
M      6
F      5
NaN    1
Name: count, dtype: int64

In [53]:
data['edad'].value_counts()

edad
24    1
25    1
32    1
45    1
52    1
20    1
28    1
38    1
41    1
19    1
35    1
29    1
Name: count, dtype: int64

In [54]:
# Incluya los valores faltantes en el conteo
#dropna: drop nan - eliminar los valores nulos
data["sexo"].value_counts(dropna = False)

sexo
M      6
F      5
NaN    1
Name: count, dtype: int64

In [55]:
# ¿Cuál es la proporción de hombres y mujeres tenemos?
data["sexo"].value_counts(normalize = True)

sexo
M    0.545455
F    0.454545
Name: proportion, dtype: float64

Los métodos `.iloc` y ``.loc`` son utilizados en Pandas para acceder a los datos de un dataframe de diferentes maneras.

`.iloc` se utiliza para acceder a los datos del dataframe mediante índices enteros. Permite seleccionar filas y columnas utilizando números enteros en lugar de etiquetas de fila y columna. La sintaxis general para utilizar `.iloc` es la siguiente:

```python
dataframe.iloc[filas, columnas]
```

Donde `filas` y `columnas` son listas o arrays de números enteros que indican las filas y columnas que se desean seleccionar, respectivamente.

<center>
<div>
<img src="img/iloc2.png" width="500"/>
</div>
</center>

Por ejemplo, para seleccionar las primeras 3 filas y las primeras 2 columnas de un dataframe, se puede utilizar el siguiente código:

```python 
dataframe.iloc[:3, :2]
```

Recuerde que la indexación en python empieza en 0. A continuación puede encontrar una referencia gráfica:
<center>
<img src="img/iloc1.png" alt="indexación" width="450" height="200">
</center>

Por otro lado, `.loc` se utiliza para acceder a los datos del dataframe mediante etiquetas de fila y columna. Permite seleccionar filas y columnas utilizando las etiquetas de fila y columna en lugar de índices enteros. La sintaxis general para utilizar `.loc` es la siguiente:

```python
dataframe.loc[filas, columnas]
```

Donde `filas` y `columnas` son listas o arrays de etiquetas de fila y columna que indican las filas y columnas que se desean seleccionar, respectivamente.

<center>
<div>
<img src="img/iloc3.png" width="500"/>
</div>
</center>

Por ejemplo, para seleccionar todas las filas donde la columna "edad" es mayor o igual a 30, se puede utilizar el siguiente código:

```python
dataframe.loc[dataframe['edad'] >= 30, :]
```

En resumen, `.iloc` se utiliza para acceder a los datos mediante índices enteros, mientras que `.loc` se utiliza para acceder a los datos mediante etiquetas de fila y columna. Ambos métodos son muy útiles para la selección y manipulación de datos en Pandas.

In [56]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70
Maria      F    28    58
Carlos     M    38    90
Laura      F    41    65
Pedro      M    19    68
Sofia      F    35    62
Andres     M    29    78

In [57]:
data.iloc[1:3,1:]

         edad  peso
nombres
Esteban    25    80
Elena      32    60

In [58]:
# Extraiga la fila de Ana usando .loc
data.loc['Ana',['edad','sexo']]

edad    45
sexo     F
Name: Ana, dtype: object

In [59]:
data.loc[data.edad == 45]

        sexo  edad  peso
nombres
Ana        F    45    86

In [60]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70
Maria      F    28    58
Carlos     M    38    90
Laura      F    41    65
Pedro      M    19    68
Sofia      F    35    62
Andres     M    29    78

In [61]:
data.loc['Ana',:]

sexo     F
edad    45
peso    86
Name: Ana, dtype: object

In [ ]:
# Extraiga la columna de edad usando .loc
data.loc[:,'edad']

In [ ]:
# Extraiga los pesos de Juan y Esteban usando .loc
data.loc[['Juan', 'Esteban'], ['peso','edad']]

In [ ]:
data

¿Recuerdan los condicionales? Las ``preguntas`` nos sirven para indexar la base de datos sobre condiciones específicas en las columnas!

In [66]:
data['edad']>30

nombres
Jose       False
Esteban    False
Elena       True
Ana         True
Julian      True
Juan       False
Maria      False
Carlos      True
Laura       True
Pedro      False
Sofia       True
Andres     False
Name: edad, dtype: bool

In [67]:
data.loc[data['edad']>30,:]

        sexo  edad  peso
nombres
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Carlos     M    38    90
Laura      F    41    65
Sofia      F    35    62

In [68]:
data.loc[data['peso']>70]

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Ana        F    45    86
Julian     M    52    72
Carlos     M    38    90
Andres     M    29    78

In [69]:
data.loc[(data['edad'] > 30) & (data['sexo'] == 'M')]

        sexo  edad  peso
nombres
Julian     M    52    72
Carlos     M    38    90

In [70]:
# Extraiga a todas las personas de sexo masculino mayores a 30 años
data.loc[(data['edad'] > 30) | (data['sexo'] == 'M'),:]

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Carlos     M    38    90
Laura      F    41    65
Pedro      M    19    68
Sofia      F    35    62
Andres     M    29    78

In [71]:
data.loc[(data['edad'] > 30) & (data['sexo'] == 'M')]

        sexo  edad  peso
nombres
Julian     M    52    72
Carlos     M    38    90

In [72]:
data

        sexo  edad  peso
nombres
Jose       M    24    75
Esteban    M    25    80
Elena      F    32    60
Ana        F    45    86
Julian     M    52    72
Juan     NaN    20    70
Maria      F    28    58
Carlos     M    38    90
Laura      F    41    65
Pedro      M    19    68
Sofia      F    35    62
Andres     M    29    78

In [73]:
# Extraiga la segunda fila usando .iloc
data.iloc[1]

sexo     M
edad    25
peso    80
Name: Esteban, dtype: object

In [74]:
data.iloc[1,]

sexo     M
edad    25
peso    80
Name: Esteban, dtype: object

In [75]:
# Extraiga la segunda y tercera columna usando .iloc
data.iloc[:,[1,2]]

         edad  peso
nombres
Jose       24    75
Esteban    25    80
Elena      32    60
Ana        45    86
Julian     52    72
Juan       20    70
Maria      28    58
Carlos     38    90
Laura      41    65
Pedro      19    68
Sofia      35    62
Andres     29    78

In [76]:
# Extraiga la primera y última fila y segunda columna usando .iloc
data.iloc[[0,-1],[1]]

         edad
nombres
Jose       24
Andres     29

In [77]:
# Reinicie el índice
data.reset_index(inplace = True, drop = False) 
data

    nombres sexo  edad  peso
0      Jose    M    24    75
1   Esteban    M    25    80
2     Elena    F    32    60
3       Ana    F    45    86
4    Julian    M    52    72
5      Juan  NaN    20    70
6     Maria    F    28    58
7    Carlos    M    38    90
8     Laura    F    41    65
9     Pedro    M    19    68
10    Sofia    F    35    62
11   Andres    M    29    78

In [78]:
data.loc[data['nombres']=='Ana']#[['sexo', 'peso']]

  nombres sexo  edad  peso
3     Ana    F    45    86

## Pandas intermedio

### Modificación de valores
Las columnas dentro de un dataframe a su vez son un objeto. Estos se conocen como `Series` y son una estructura de datos unidimensional que contiene una secuencia de valores y una etiqueta de índice para cada uno de ellos. Se puede pensar en una serie como una columna en una hoja de cálculo o como un array unidimensional con etiquetas de índice.

Una serie de Pandas se puede crear a partir de una lista, un array NumPy, un diccionario o incluso otro objeto de serie. La etiqueta de índice por defecto para cada elemento de la serie es simplemente un rango de números enteros de 0 a n-1, donde n es el número de elementos en la serie. Sin embargo, se puede especificar etiquetas de índice personalizadas para cada elemento de la serie.

In [79]:
type(data["nombres"])

pandas.core.series.Series

In [80]:
data

    nombres sexo  edad  peso
0      Jose    M    24    75
1   Esteban    M    25    80
2     Elena    F    32    60
3       Ana    F    45    86
4    Julian    M    52    72
5      Juan  NaN    20    70
6     Maria    F    28    58
7    Carlos    M    38    90
8     Laura    F    41    65
9     Pedro    M    19    68
10    Sofia    F    35    62
11   Andres    M    29    78

Podemos comenzar editando valores o celdas particulares. Por ejemplo, el sexo de Juan está como nulo. Vamos a definirlo como masculino

In [81]:
data.loc[data.nombres == "Juan", "sexo"]

5    NaN
Name: sexo, dtype: object

In [82]:
data.loc[data.nombres == "Juan", "sexo"] = "M"

In [83]:
data

    nombres sexo  edad  peso
0      Jose    M    24    75
1   Esteban    M    25    80
2     Elena    F    32    60
3       Ana    F    45    86
4    Julian    M    52    72
5      Juan    M    20    70
6     Maria    F    28    58
7    Carlos    M    38    90
8     Laura    F    41    65
9     Pedro    M    19    68
10    Sofia    F    35    62
11   Andres    M    29    78

Del mismo modo, también podemos editar columnas. Actualmente tenemos la edad en años, pasemosla a días.

In [84]:
data["edad"]*365

0      8760
1      9125
2     11680
3     16425
4     18980
5      7300
6     10220
7     13870
8     14965
9      6935
10    12775
11    10585
Name: edad, dtype: int64

In [85]:
data["edad"] = data["edad"]*365

In [86]:
data

    nombres sexo   edad  peso
0      Jose    M   8760    75
1   Esteban    M   9125    80
2     Elena    F  11680    60
3       Ana    F  16425    86
4    Julian    M  18980    72
5      Juan    M   7300    70
6     Maria    F  10220    58
7    Carlos    M  13870    90
8     Laura    F  14965    65
9     Pedro    M   6935    68
10    Sofia    F  12775    62
11   Andres    M  10585    78

También podemos crear una nueva variable

In [87]:
import numpy as np
data["nueva_variable"] = [1,2,3,np.nan,np.nan,np.nan,7,8,9,np.nan,np.nan,np.nan]

In [88]:
data

    nombres sexo   edad  peso  nueva_variable
0      Jose    M   8760    75             1.0
1   Esteban    M   9125    80             2.0
2     Elena    F  11680    60             3.0
3       Ana    F  16425    86             NaN
4    Julian    M  18980    72             NaN
5      Juan    M   7300    70             NaN
6     Maria    F  10220    58             7.0
7    Carlos    M  13870    90             8.0
8     Laura    F  14965    65             9.0
9     Pedro    M   6935    68             NaN
10    Sofia    F  12775    62             NaN
11   Andres    M  10585    78             NaN

Otro método para crear una nueva variable es usando el método `.assign()`

In [89]:
data = data.assign(nueva_variable2 = np.nan)
data

    nombres sexo   edad  peso  nueva_variable  nueva_variable2
0      Jose    M   8760    75             1.0              NaN
1   Esteban    M   9125    80             2.0              NaN
2     Elena    F  11680    60             3.0              NaN
3       Ana    F  16425    86             NaN              NaN
4    Julian    M  18980    72             NaN              NaN
5      Juan    M   7300    70             NaN              NaN
6     Maria    F  10220    58             7.0              NaN
7    Carlos    M  13870    90             8.0              NaN
8     Laura    F  14965    65             9.0              NaN
9     Pedro    M   6935    68             NaN              NaN
10    Sofia    F  12775    62             NaN              NaN
11   Andres    M  10585    78             NaN              NaN

In [90]:
data['edad'] = data['edad']/365
data['edad_dias'] = data['edad']*365

In [91]:
data

    nombres sexo  edad  peso  nueva_variable  nueva_variable2  edad_dias
0      Jose    M  24.0    75             1.0              NaN     8760.0
1   Esteban    M  25.0    80             2.0              NaN     9125.0
2     Elena    F  32.0    60             3.0              NaN    11680.0
3       Ana    F  45.0    86             NaN              NaN    16425.0
4    Julian    M  52.0    72             NaN              NaN    18980.0
5      Juan    M  20.0    70             NaN              NaN     7300.0
6     Maria    F  28.0    58             7.0              NaN    10220.0
7    Carlos    M  38.0    90             8.0              NaN    13870.0
8     Laura    F  41.0    65             9.0              NaN    14965.0
9     Pedro    M  19.0    68             NaN              NaN     6935.0
10    Sofia    F  35.0    62             NaN              NaN    12775.0
11   Andres    M  29.0    78             NaN              NaN    10585.0

In [92]:
data.loc[data.edad<=24,'nueva_variable'] = 'Rango 1: 18-24'

C:\Users\Santiago Neira\AppData\Local\Temp\ipykernel_40448\4244016696.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Rango 1: 18-24' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data.loc[data.edad<=24,'nueva_variable'] = 'Rango 1: 18-24'

In [93]:
data.loc[data.edad<=24,'nueva_variable'] = 'Rango 1: 18-24'
data.loc[(data.edad>=25) & (data.edad<=32),'nueva_variable'] = 'Rango 2: 25-32'
data.loc[(data.edad>=33) & (data.edad<=54),'nueva_variable'] = 'Rango 3: 33-54'
data.loc[(data.edad>=55),'nueva_variable'] = 'Rango 4: 55+'
data

    nombres sexo  edad  peso  nueva_variable  nueva_variable2  edad_dias
0      Jose    M  24.0    75  Rango 1: 18-24              NaN     8760.0
1   Esteban    M  25.0    80  Rango 2: 25-32              NaN     9125.0
2     Elena    F  32.0    60  Rango 2: 25-32              NaN    11680.0
3       Ana    F  45.0    86  Rango 3: 33-54              NaN    16425.0
4    Julian    M  52.0    72  Rango 3: 33-54              NaN    18980.0
5      Juan    M  20.0    70  Rango 1: 18-24              NaN     7300.0
6     Maria    F  28.0    58  Rango 2: 25-32              NaN    10220.0
7    Carlos    M  38.0    90  Rango 3: 33-54              NaN    13870.0
8     Laura    F  41.0    65  Rango 3: 33-54              NaN    14965.0
9     Pedro    M  19.0    68  Rango 1: 18-24              NaN     6935.0
10    Sofia    F  35.0    62  Rango 3: 33-54              NaN    12775.0
11   Andres    M  29.0    78  Rango 2: 25-32              NaN    10585.0

El valor con el que se modifica cada variable no tiene que ser el mismo para todas.

In [94]:
apellido = ["Urrutia", "Carvajal", "Gómez", "Tobón", "Pardo", "Lopez", "Martinez", "Rodriguez", "Garcia", "Hernandez", "Diaz", "Moreno"]

In [95]:
data["nombres"] = data["nombres"] + " " + apellido

In [96]:
data

,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,Jose Urrutia,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,Esteban Carvajal,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,Elena Gómez,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,Ana Tobón,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,Julian Pardo,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,Juan Lopez,M,20.0,70,Rango 1: 18-24,NaN,7300.0
6,Maria Martinez,F,28.0,58,Rango 2: 25-32,NaN,10220.0
7,Carlos Rodriguez,M,38.0,90,Rango 3: 33-54,NaN,13870.0
8,Laura Garcia,F,41.0,65,Rango 3: 33-54,NaN,14965.0
9,Pedro Hernandez,M,19.0,68,Rango 1: 18-24,NaN,6935.0
10,Sofia Diaz,F,35.0,62,Rango 3: 33-54,NaN,12775.0
11,Andres Moreno,M,29.0,78,Rango 2: 25-32,NaN,10585.0

### Estadísticas descriptivas
Anteriormente pudimos ver como el método `.describe()` me daba un resumen de toda la base. Sin embargo, en esta sección veremos cada una de las principales funciones para sacar las estadísticas

In [97]:
data.describe()

            edad       peso  nueva_variable2     edad_dias
count  12.000000  12.000000              0.0     12.000000
mean   32.333333  72.000000              NaN  11801.666667
std    10.201010  10.171261              NaN   3723.368669
min    19.000000  58.000000              NaN   6935.000000
25%    24.750000  64.250000              NaN   9033.750000
50%    30.500000  71.000000              NaN  11132.500000
75%    38.750000  78.500000              NaN  14143.750000
max    52.000000  90.000000              NaN  18980.000000

In [98]:
# Suma de todas las columnas
data.sum(axis=0)

nombres            Jose UrrutiaEsteban CarvajalElena GómezAna Tob...
sexo                                                    MMFFMMFMFMFM
edad                                                           388.0
peso                                                             864
nueva_variable     Rango 1: 18-24Rango 2: 25-32Rango 2: 25-32Rang...
nueva_variable2                                                  0.0
edad_dias                                                   141620.0
dtype: object

In [99]:
data

,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,Jose Urrutia,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,Esteban Carvajal,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,Elena Gómez,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,Ana Tobón,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,Julian Pardo,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,Juan Lopez,M,20.0,70,Rango 1: 18-24,NaN,7300.0
6,Maria Martinez,F,28.0,58,Rango 2: 25-32,NaN,10220.0
7,Carlos Rodriguez,M,38.0,90,Rango 3: 33-54,NaN,13870.0
8,Laura Garcia,F,41.0,65,Rango 3: 33-54,NaN,14965.0
9,Pedro Hernandez,M,19.0,68,Rango 1: 18-24,NaN,6935.0
10,Sofia Diaz,F,35.0,62,Rango 3: 33-54,NaN,12775.0
11,Andres Moreno,M,29.0,78,Rango 2: 25-32,NaN,10585.0

In [100]:
# Suma por fila
data.sum(axis = 1, numeric_only = True)

0      8859.0
1      9230.0
2     11772.0
3     16556.0
4     19104.0
5      7390.0
6     10306.0
7     13998.0
8     15071.0
9      7022.0
10    12872.0
11    10692.0
dtype: float64

In [101]:
# Suma de toda la columna peso
data["peso"].sum()

np.int64(864)

In [102]:
# Dato mínimo por columna
data.min()

nombres                 Ana Tobón
sexo                            F
edad                         19.0
peso                           58
nueva_variable     Rango 1: 18-24
nueva_variable2               NaN
edad_dias                  6935.0
dtype: object

In [103]:
# Dato máximo por columna
data.max()

nombres                Sofia Diaz
sexo                            M
edad                         52.0
peso                           90
nueva_variable     Rango 3: 33-54
nueva_variable2               NaN
edad_dias                 18980.0
dtype: object

In [104]:
data

,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,Jose Urrutia,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,Esteban Carvajal,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,Elena Gómez,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,Ana Tobón,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,Julian Pardo,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,Juan Lopez,M,20.0,70,Rango 1: 18-24,NaN,7300.0
6,Maria Martinez,F,28.0,58,Rango 2: 25-32,NaN,10220.0
7,Carlos Rodriguez,M,38.0,90,Rango 3: 33-54,NaN,13870.0
8,Laura Garcia,F,41.0,65,Rango 3: 33-54,NaN,14965.0
9,Pedro Hernandez,M,19.0,68,Rango 1: 18-24,NaN,6935.0
10,Sofia Diaz,F,35.0,62,Rango 3: 33-54,NaN,12775.0
11,Andres Moreno,M,29.0,78,Rango 2: 25-32,NaN,10585.0

In [105]:
# ¿Cuál es el id de la persona que tiene la edad mínima?
data.edad.idxmin()

9

In [106]:
# Juan López tiene la edad mínima
data.iloc[data.edad.idxmin(),]

nombres            Pedro Hernandez
sexo                             M
edad                          19.0
peso                            68
nueva_variable      Rango 1: 18-24
nueva_variable2                NaN
edad_dias                   6935.0
Name: 9, dtype: object

In [107]:
# ¿Cuál es el índice de la persona con mayor peso?
data.peso.idxmax()

7

In [108]:
data.loc[data.peso.idxmax(),]

nombres            Carlos Rodriguez
sexo                              M
edad                           38.0
peso                             90
nueva_variable       Rango 3: 33-54
nueva_variable2                 NaN
edad_dias                   13870.0
Name: 7, dtype: object

In [109]:
# Media de las variables
data.mean(numeric_only = True)

edad                  32.333333
peso                  72.000000
nueva_variable2             NaN
edad_dias          11801.666667
dtype: float64

In [110]:
data

,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,Jose Urrutia,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,Esteban Carvajal,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,Elena Gómez,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,Ana Tobón,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,Julian Pardo,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,Juan Lopez,M,20.0,70,Rango 1: 18-24,NaN,7300.0
6,Maria Martinez,F,28.0,58,Rango 2: 25-32,NaN,10220.0
7,Carlos Rodriguez,M,38.0,90,Rango 3: 33-54,NaN,13870.0
8,Laura Garcia,F,41.0,65,Rango 3: 33-54,NaN,14965.0
9,Pedro Hernandez,M,19.0,68,Rango 1: 18-24,NaN,6935.0
10,Sofia Diaz,F,35.0,62,Rango 3: 33-54,NaN,12775.0
11,Andres Moreno,M,29.0,78,Rango 2: 25-32,NaN,10585.0

In [111]:
# Datos medianos
data.median(numeric_only = True)

edad                  30.5
peso                  71.0
nueva_variable2        NaN
edad_dias          11132.5
dtype: float64

In [112]:
data.reset_index(inplace=True)

In [113]:
data['nombres'] = data['nombres'] + ' López'

In [114]:
data

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia López,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,1,Esteban Carvajal López,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,2,Elena Gómez López,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,3,Ana Tobón López,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,4,Julian Pardo López,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,5,Juan Lopez López,M,20.0,70,Rango 1: 18-24,NaN,7300.0
6,6,Maria Martinez López,F,28.0,58,Rango 2: 25-32,NaN,10220.0
7,7,Carlos Rodriguez López,M,38.0,90,Rango 3: 33-54,NaN,13870.0
8,8,Laura Garcia López,F,41.0,65,Rango 3: 33-54,NaN,14965.0
9,9,Pedro Hernandez López,M,19.0,68,Rango 1: 18-24,NaN,6935.0
10,10,Sofia Diaz López,F,35.0,62,Rango 3: 33-54,NaN,12775.0
11,11,Andres Moreno López,M,29.0,78,Rango 2: 25-32,NaN,10585.0

In [115]:
data.set_index('nombres')

,index,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
nombres,,,,,,,
Jose Urrutia López,0,M,24.0,75,Rango 1: 18-24,NaN,8760.0
Esteban Carvajal López,1,M,25.0,80,Rango 2: 25-32,NaN,9125.0
Elena Gómez López,2,F,32.0,60,Rango 2: 25-32,NaN,11680.0
Ana Tobón López,3,F,45.0,86,Rango 3: 33-54,NaN,16425.0
Julian Pardo López,4,M,52.0,72,Rango 3: 33-54,NaN,18980.0
Juan Lopez López,5,M,20.0,70,Rango 1: 18-24,NaN,7300.0
Maria Martinez López,6,F,28.0,58,Rango 2: 25-32,NaN,10220.0
Carlos Rodriguez López,7,M,38.0,90,Rango 3: 33-54,NaN,13870.0
Laura Garcia López,8,F,41.0,65,Rango 3: 33-54,NaN,14965.0
Pedro Hernandez López,9,M,19.0,68,Rango 1: 18-24,NaN,6935.0
Sofia Diaz López,10,F,35.0,62,Rango 3: 33-54,NaN,12775.0
Andres Moreno López,11,M,29.0,78,Rango 2: 25-32,NaN,10585.0

### Aplicar funciones a las columnas
En Pandas, el método `apply` se utiliza para aplicar una función a una serie o a un dataframe. El método `apply` toma como argumento una función y la aplica a cada elemento de la serie o del dataframe, devolviendo una nueva serie o dataframe con los resultados de la función aplicada a cada elemento.

La función que se aplica en el método `apply` puede ser una función lambda o una función definida por el usuario. Esta función debe tomar como argumento un elemento de la serie o dataframe y devolver el resultado de aplicar la función al elemento.

El método `apply` se puede aplicar de varias formas en un dataframe:

- Aplicar una función a una columna específica: Se puede utilizar el método `apply` en una columna específica de un dataframe utilizando la siguiente sintaxis:

```python
dataframe["nombre_columna"].apply(funcion)
```

Donde "nombre_columna" es el nombre de la columna en la que se desea aplicar la función y "funcion" es la función que se desea aplicar a cada elemento de la columna.

- Aplicar una función a un dataframe completo: Se puede utilizar el método `apply` en un dataframe completo utilizando la siguiente sintaxis:

```python
dataframe.apply(funcion)
```

Donde "funcion" es la función que se desea aplicar a cada elemento del dataframe.

- Aplicar una función a una fila específica: Se puede utilizar el método `apply` en una fila específica de un dataframe utilizando la siguiente sintaxis:

```python
dataframe.loc[etiqueta_fila].apply(funcion)
```

Donde "etiqueta_fila" es la etiqueta de la fila en la que se desea aplicar la función y "funcion" es la función que se desea aplicar a cada elemento de la fila.

- el método `apply` también puede ser utilizado con funciones **lambda**, que son funciones anónimas y pequeñas que se definen dentro de una línea de código. Por ejemplo, si se quisiera aplicar una función **lambda** que tome como entrada una cadena de caracteres y devuelva la versión en mayúsculas de la misma, se podría utilizar el método apply de la siguiente manera:

```python
dataframe['nombre_columna'].apply(lambda x: x.upper())
```

<center>
<div>
<img src="img/lambda.png" width="200"/>
</div>

<div>
<img src="img/lambda1.png" width="200"/>
</div>
</center>

El método `apply` también puede aplicarse a múltiples columnas o filas utilizando la opción axis. Si `axis=0`, la función se aplicará a cada columna del dataframe. Si `axis=1`, la función se aplicará a cada fila del dataframe.

En resumen, el método `apply` se utiliza en Pandas para aplicar una función a una serie o dataframe, y puede utilizarse de diferentes maneras para aplicar la función.

In [116]:
data

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia López,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,1,Esteban Carvajal López,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,2,Elena Gómez López,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,3,Ana Tobón López,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,4,Julian Pardo López,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,5,Juan Lopez López,M,20.0,70,Rango 1: 18-24,NaN,7300.0
6,6,Maria Martinez López,F,28.0,58,Rango 2: 25-32,NaN,10220.0
7,7,Carlos Rodriguez López,M,38.0,90,Rango 3: 33-54,NaN,13870.0
8,8,Laura Garcia López,F,41.0,65,Rango 3: 33-54,NaN,14965.0
9,9,Pedro Hernandez López,M,19.0,68,Rango 1: 18-24,NaN,6935.0
10,10,Sofia Diaz López,F,35.0,62,Rango 3: 33-54,NaN,12775.0
11,11,Andres Moreno López,M,29.0,78,Rango 2: 25-32,NaN,10585.0

In [117]:
# Multiplicar x 2 todas las celdas
data.apply(lambda i: i*2)

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia LópezJose Urrutia López,MM,48.0,150,Rango 1: 18-24Rango 1: 18-24,NaN,17520.0
1,2,Esteban Carvajal LópezEsteban Carvajal López,MM,50.0,160,Rango 2: 25-32Rango 2: 25-32,NaN,18250.0
2,4,Elena Gómez LópezElena Gómez López,FF,64.0,120,Rango 2: 25-32Rango 2: 25-32,NaN,23360.0
3,6,Ana Tobón LópezAna Tobón López,FF,90.0,172,Rango 3: 33-54Rango 3: 33-54,NaN,32850.0
4,8,Julian Pardo LópezJulian Pardo López,MM,104.0,144,Rango 3: 33-54Rango 3: 33-54,NaN,37960.0
5,10,Juan Lopez LópezJuan Lopez López,MM,40.0,140,Rango 1: 18-24Rango 1: 18-24,NaN,14600.0
6,12,Maria Martinez LópezMaria Martinez López,FF,56.0,116,Rango 2: 25-32Rango 2: 25-32,NaN,20440.0
7,14,Carlos Rodriguez LópezCarlos Rodriguez López,MM,76.0,180,Rango 3: 33-54Rango 3: 33-54,NaN,27740.0
8,16,Laura Garcia LópezLaura Garcia López,FF,82.0,130,Rango 3: 33-54Rango 3: 33-54,NaN,29930.0
9,18,Pedro Hernandez LópezPedro Hernandez López,MM,38.0,136,Rango 1: 18-24Rango 1: 18-24,NaN,13870.0
10,20,Sofia Diaz LópezSofia Diaz López,FF,70.0,124,Rango 3: 33-54Rango 3: 33-54,NaN,25550.0
11,22,Andres Moreno LópezAndres Moreno López,MM,58.0,156,Rango 2: 25-32Rango 2: 25-32,NaN,21170.0

In [118]:
# Convertir la edad de días a años
data["edad_dias"].apply(lambda x: x/365)

0     24.0
1     25.0
2     32.0
3     45.0
4     52.0
5     20.0
6     28.0
7     38.0
8     41.0
9     19.0
10    35.0
11    29.0
Name: edad_dias, dtype: float64

In [119]:
def funcion_ayuda(x):
    return x/365

In [120]:
data.edad_dias.apply(funcion_ayuda)

0     24.0
1     25.0
2     32.0
3     45.0
4     52.0
5     20.0
6     28.0
7     38.0
8     41.0
9     19.0
10    35.0
11    29.0
Name: edad_dias, dtype: float64

In [121]:
data[['edad','peso']].apply(np.mean)

edad    32.333333
peso    72.000000
dtype: float64

In [122]:
data[['edad','peso']].max()

edad    52.0
peso    90.0
dtype: float64

### Eliminar filas y columnas

In [123]:
data

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia López,M,24.0,75,Rango 1: 18-24,NaN,8760.0
1,1,Esteban Carvajal López,M,25.0,80,Rango 2: 25-32,NaN,9125.0
2,2,Elena Gómez López,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,3,Ana Tobón López,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,4,Julian Pardo López,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,5,Juan Lopez López,M,20.0,70,Rango 1: 18-24,NaN,7300.0
6,6,Maria Martinez López,F,28.0,58,Rango 2: 25-32,NaN,10220.0
7,7,Carlos Rodriguez López,M,38.0,90,Rango 3: 33-54,NaN,13870.0
8,8,Laura Garcia López,F,41.0,65,Rango 3: 33-54,NaN,14965.0
9,9,Pedro Hernandez López,M,19.0,68,Rango 1: 18-24,NaN,6935.0
10,10,Sofia Diaz López,F,35.0,62,Rango 3: 33-54,NaN,12775.0
11,11,Andres Moreno López,M,29.0,78,Rango 2: 25-32,NaN,10585.0

In [124]:
# Borre la fila identificada como 1
data.drop(1)

,index,nombres,sexo,edad,peso,nueva_variable,nueva_variable2,edad_dias
0,0,Jose Urrutia López,M,24.0,75,Rango 1: 18-24,NaN,8760.0
2,2,Elena Gómez López,F,32.0,60,Rango 2: 25-32,NaN,11680.0
3,3,Ana Tobón López,F,45.0,86,Rango 3: 33-54,NaN,16425.0
4,4,Julian Pardo López,M,52.0,72,Rango 3: 33-54,NaN,18980.0
5,5,Juan Lopez López,M,20.0,70,Rango 1: 18-24,NaN,7300.0
6,6,Maria Martinez López,F,28.0,58,Rango 2: 25-32,NaN,10220.0
7,7,Carlos Rodriguez López,M,38.0,90,Rango 3: 33-54,NaN,13870.0
8,8,Laura Garcia López,F,41.0,65,Rango 3: 33-54,NaN,14965.0
9,9,Pedro Hernandez López,M,19.0,68,Rango 1: 18-24,NaN,6935.0
10,10,Sofia Diaz López,F,35.0,62,Rango 3: 33-54,NaN,12775.0
11,11,Andres Moreno López,M,29.0,78,Rango 2: 25-32,NaN,10585.0

In [125]:
# Borre la columna nueva_variable y nueva_variable2
data.drop(columns = ["index", "nueva_variable2"], inplace = True)

In [126]:
data

                   nombres sexo  edad  peso  nueva_variable  edad_dias
0       Jose Urrutia López    M  24.0    75  Rango 1: 18-24     8760.0
1   Esteban Carvajal López    M  25.0    80  Rango 2: 25-32     9125.0
2        Elena Gómez López    F  32.0    60  Rango 2: 25-32    11680.0
3          Ana Tobón López    F  45.0    86  Rango 3: 33-54    16425.0
4       Julian Pardo López    M  52.0    72  Rango 3: 33-54    18980.0
5         Juan Lopez López    M  20.0    70  Rango 1: 18-24     7300.0
6     Maria Martinez López    F  28.0    58  Rango 2: 25-32    10220.0
7   Carlos Rodriguez López    M  38.0    90  Rango 3: 33-54    13870.0
8       Laura Garcia López    F  41.0    65  Rango 3: 33-54    14965.0
9    Pedro Hernandez López    M  19.0    68  Rango 1: 18-24     6935.0
10        Sofia Diaz López    F  35.0    62  Rango 3: 33-54    12775.0
11     Andres Moreno López    M  29.0    78  Rango 2: 25-32    10585.0

In [127]:
# Creemos un valor faltante
data.loc[0, "nombres"] = np.nan

In [128]:
data

                   nombres sexo  edad  peso  nueva_variable  edad_dias
0                      NaN    M  24.0    75  Rango 1: 18-24     8760.0
1   Esteban Carvajal López    M  25.0    80  Rango 2: 25-32     9125.0
2        Elena Gómez López    F  32.0    60  Rango 2: 25-32    11680.0
3          Ana Tobón López    F  45.0    86  Rango 3: 33-54    16425.0
4       Julian Pardo López    M  52.0    72  Rango 3: 33-54    18980.0
5         Juan Lopez López    M  20.0    70  Rango 1: 18-24     7300.0
6     Maria Martinez López    F  28.0    58  Rango 2: 25-32    10220.0
7   Carlos Rodriguez López    M  38.0    90  Rango 3: 33-54    13870.0
8       Laura Garcia López    F  41.0    65  Rango 3: 33-54    14965.0
9    Pedro Hernandez López    M  19.0    68  Rango 1: 18-24     6935.0
10        Sofia Diaz López    F  35.0    62  Rango 3: 33-54    12775.0
11     Andres Moreno López    M  29.0    78  Rango 2: 25-32    10585.0

In [129]:
# Eliminamos las filas con valores faltantes
data.dropna()

                   nombres sexo  edad  peso  nueva_variable  edad_dias
1   Esteban Carvajal López    M  25.0    80  Rango 2: 25-32     9125.0
2        Elena Gómez López    F  32.0    60  Rango 2: 25-32    11680.0
3          Ana Tobón López    F  45.0    86  Rango 3: 33-54    16425.0
4       Julian Pardo López    M  52.0    72  Rango 3: 33-54    18980.0
5         Juan Lopez López    M  20.0    70  Rango 1: 18-24     7300.0
6     Maria Martinez López    F  28.0    58  Rango 2: 25-32    10220.0
7   Carlos Rodriguez López    M  38.0    90  Rango 3: 33-54    13870.0
8       Laura Garcia López    F  41.0    65  Rango 3: 33-54    14965.0
9    Pedro Hernandez López    M  19.0    68  Rango 1: 18-24     6935.0
10        Sofia Diaz López    F  35.0    62  Rango 3: 33-54    12775.0
11     Andres Moreno López    M  29.0    78  Rango 2: 25-32    10585.0

Agreguemos una nueva fila al DataFrame para luego demostrar el método `drop_duplicates()`.

In [130]:
# Creemos una fila duplicada (copiamos la fila en posición 1)
data.loc[len(data)] = data.iloc[1].values

In [131]:
data

                   nombres sexo  edad  peso  nueva_variable  edad_dias
0                      NaN    M  24.0    75  Rango 1: 18-24     8760.0
1   Esteban Carvajal López    M  25.0    80  Rango 2: 25-32     9125.0
2        Elena Gómez López    F  32.0    60  Rango 2: 25-32    11680.0
3          Ana Tobón López    F  45.0    86  Rango 3: 33-54    16425.0
4       Julian Pardo López    M  52.0    72  Rango 3: 33-54    18980.0
5         Juan Lopez López    M  20.0    70  Rango 1: 18-24     7300.0
6     Maria Martinez López    F  28.0    58  Rango 2: 25-32    10220.0
7   Carlos Rodriguez López    M  38.0    90  Rango 3: 33-54    13870.0
8       Laura Garcia López    F  41.0    65  Rango 3: 33-54    14965.0
9    Pedro Hernandez López    M  19.0    68  Rango 1: 18-24     6935.0
10        Sofia Diaz López    F  35.0    62  Rango 3: 33-54    12775.0
11     Andres Moreno López    M  29.0    78  Rango 2: 25-32    10585.0
12  Esteban Carvajal López    M  25.0    80  Rango 2: 25-32     9125.0

In [132]:
# Eliminemos duplicados. Conserva la primera observación
data = data.drop_duplicates()
data

                   nombres sexo  edad  peso  nueva_variable  edad_dias
0                      NaN    M  24.0    75  Rango 1: 18-24     8760.0
1   Esteban Carvajal López    M  25.0    80  Rango 2: 25-32     9125.0
2        Elena Gómez López    F  32.0    60  Rango 2: 25-32    11680.0
3          Ana Tobón López    F  45.0    86  Rango 3: 33-54    16425.0
4       Julian Pardo López    M  52.0    72  Rango 3: 33-54    18980.0
5         Juan Lopez López    M  20.0    70  Rango 1: 18-24     7300.0
6     Maria Martinez López    F  28.0    58  Rango 2: 25-32    10220.0
7   Carlos Rodriguez López    M  38.0    90  Rango 3: 33-54    13870.0
8       Laura Garcia López    F  41.0    65  Rango 3: 33-54    14965.0
9    Pedro Hernandez López    M  19.0    68  Rango 1: 18-24     6935.0
10        Sofia Diaz López    F  35.0    62  Rango 3: 33-54    12775.0
11     Andres Moreno López    M  29.0    78  Rango 2: 25-32    10585.0

In [133]:
data.reset_index(drop=True,inplace=True)
data

                   nombres sexo  edad  peso  nueva_variable  edad_dias
0                      NaN    M  24.0    75  Rango 1: 18-24     8760.0
1   Esteban Carvajal López    M  25.0    80  Rango 2: 25-32     9125.0
2        Elena Gómez López    F  32.0    60  Rango 2: 25-32    11680.0
3          Ana Tobón López    F  45.0    86  Rango 3: 33-54    16425.0
4       Julian Pardo López    M  52.0    72  Rango 3: 33-54    18980.0
5         Juan Lopez López    M  20.0    70  Rango 1: 18-24     7300.0
6     Maria Martinez López    F  28.0    58  Rango 2: 25-32    10220.0
7   Carlos Rodriguez López    M  38.0    90  Rango 3: 33-54    13870.0
8       Laura Garcia López    F  41.0    65  Rango 3: 33-54    14965.0
9    Pedro Hernandez López    M  19.0    68  Rango 1: 18-24     6935.0
10        Sofia Diaz López    F  35.0    62  Rango 3: 33-54    12775.0
11     Andres Moreno López    M  29.0    78  Rango 2: 25-32    10585.0

In [134]:
data.drop_duplicates(subset='sexo')

             nombres sexo  edad  peso  nueva_variable  edad_dias
0                NaN    M  24.0    75  Rango 1: 18-24     8760.0
2  Elena Gómez López    F  32.0    60  Rango 2: 25-32    11680.0

In [135]:
data

                   nombres sexo  edad  peso  nueva_variable  edad_dias
0                      NaN    M  24.0    75  Rango 1: 18-24     8760.0
1   Esteban Carvajal López    M  25.0    80  Rango 2: 25-32     9125.0
2        Elena Gómez López    F  32.0    60  Rango 2: 25-32    11680.0
3          Ana Tobón López    F  45.0    86  Rango 3: 33-54    16425.0
4       Julian Pardo López    M  52.0    72  Rango 3: 33-54    18980.0
5         Juan Lopez López    M  20.0    70  Rango 1: 18-24     7300.0
6     Maria Martinez López    F  28.0    58  Rango 2: 25-32    10220.0
7   Carlos Rodriguez López    M  38.0    90  Rango 3: 33-54    13870.0
8       Laura Garcia López    F  41.0    65  Rango 3: 33-54    14965.0
9    Pedro Hernandez López    M  19.0    68  Rango 1: 18-24     6935.0
10        Sofia Diaz López    F  35.0    62  Rango 3: 33-54    12775.0
11     Andres Moreno López    M  29.0    78  Rango 2: 25-32    10585.0

## Ejercicio 1

Para el siguiente ejercicio, usted importará el archivo `consumo_masivo_col.xslx`. Este dataset contiene los productos disponibles en los dos supermercados más grandes de Colombia, en el se incluye la marca, producto, precio en diferentes puntos de corte durante el año 2019. Primero, una introducción a como leer este archivo.

In [ ]:
!pip3 install openpyxl

In [ ]:
#ruta_archivo = '/content/consumo_masivo_col.xlsx' #Para GoogleColab
ruta_archivo = './datos/consumo_masivo_col.xlsx' #Para local
productos_consumo_masivo = pd.read_excel(ruta_archivo)

#### Accediendo a los archivos a través del paquete os

In [ ]:
import os
os.getcwd()
#os.chdir("Ingrese_su_ruta_aqui")
#os.getcwd()

In [ ]:
productos_consumo_masivo = pd.read_excel('consumo_masivo_col.xlsx')

### Trabajando con fechas al importar un archivo de excel

In [ ]:
productos_consumo_masivo.head()

Al importar datos desde Excel, las fechas pueden llegar como números enteros (por ejemplo, `20190609` para 9 de junio de 2019) en lugar del tipo `datetime`. Para poder filtrar, ordenar y realizar operaciones con fechas, debemos convertirlas usando `pd.to_datetime()`.

**Parámetro `format`**: Indica el formato en que vienen las fechas. Los códigos más comunes son:
- `%Y` — año con 4 dígitos (ej: 2019)
- `%m` — mes con 2 dígitos (01-12)
- `%d` — día con 2 dígitos (01-31)

En este caso, `'%Y%m%d'` indica que la fecha está como `AAAAMMDD` (ej: 20190609 = 9 de junio de 2019).

> **Documentación**: [pandas.to_datetime](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html)

In [ ]:
productos_consumo_masivo['date'].head()

In [ ]:
productos_consumo_masivo['date'] = pd.to_datetime(productos_consumo_masivo['date'],format='%Y%m%d')

### Trabajando con valores numéricos al importar un archivo de excel

In [ ]:
productos_consumo_masivo['prod_unit_price'].head()

In [ ]:
productos_consumo_masivo['prod_unit_price'].dtype

In [ ]:
productos_consumo_masivo['prod_unit_price'].astype(float)

In [ ]:
productos_consumo_masivo['prod_unit_price'] = pd.to_numeric(productos_consumo_masivo['prod_unit_price'].astype(str).str.replace(',', '.'),errors='coerce')

In [ ]:
productos_consumo_masivo.head()

A partir del dataframe anterior, responda las siguientes preguntas:

1. Antes de iniciar, trate de familiarizarse un poco con la base de datos. ¿Cuántos valores de `subcategory` existen? ¿A qué corresponden? ¿Cuántos valores de `prod_units` existen? ¿A qué corresponden?
2. ¿Cuál es el rango de precios que se encuentra en esta base de datos?
3. ¿Cuál es el precio promedio de los artículos de cuidado personal?
4. ¿Cuáles son  las cinco `Galletas dulces` más costosas del mercado? ¿A qué marcas corresponden?
5. ¿Cuáles son las cinco marcas que tienen más productos por debajo de los $10,000 pesos? ¿Cuáles son? Encuentre algunos ejemplos de estos productos.
6. ¿Cuál es la categoría con más productos en el dataset? ¿Cuántos productos tiene?
7. ¿Cuántos productos tienen como fecha Febrero de 2020? ¿Cuáles son las dos marcas con más productos en esta fecha?